chore: Update images to build-6.20
Signed-off-by: Jorge Solórzano <jorsol@ongres.com>

diff --git a/stackgres-k8s/src/operator/src/main/resources/templates/exec-with-env b/stackgres-k8s/src/operator/src/main/resources/templates/exec-with-env
--- a/stackgres-k8s/src/operator/src/main/resources/templates/exec-with-env
+++ b/stackgres-k8s/src/operator/src/main/resources/templates/exec-with-env
@@ -1,11 +1,30 @@
 #!/bin/sh
 
+LC_ALL=C.UTF-8; export LC_ALL
+
 set -e
+
+verify_shell_is_posix_or_exit() {
+  if [ -n "${ZSH_VERSION+x}" ]; then
+    error "Running installation script with \`zsh\` is known to cause errors."
+    error "Please use \`sh\` instead."
+    exit 1
+  elif [ -n "${BASH_VERSION+x}" ] && [ -z "${POSIXLY_CORRECT+x}" ]; then
+    error "Running installation script with non-POSIX \`bash\` may cause errors."
+    error "Please use \`sh\` instead."
+    exit 1
+  else
+    true  # No-op: no issues detected
+  fi
+}
 
 die() {
   >&2 echo "$@"
   exit 1
 }
+
+# Non-POSIX shells can break once executing code due to semantic differences
+verify_shell_is_posix_or_exit
 
 REPLACES=""
 OVERWRITE=false
@@ -73,6 +92,8 @@ then
     eval "export ${REPLACE%=*}=\"\$${REPLACE#*=}\""
   done
 fi
+
+unset LC_ALL
 
 if [ -n "$1" ]
 then
