e2e: check backup works after restart

diff --git a/stackgres-k8s/e2e/spec/abstract/backup b/stackgres-k8s/e2e/spec/abstract/backup
--- a/stackgres-k8s/e2e/spec/abstract/backup
+++ b/stackgres-k8s/e2e/spec/abstract/backup
@@ -7,24 +7,13 @@ check_backup() {
 
   check_automatic_backup "$NODE"
 
-  if check_timelines
-  then
-    echo "SUCCESS. All timelines are correct"
-  else
-    echo "FAIL. Some timelines are not correct"
-    return 1
-  fi
+  check_timelines
 
-  if check_control_data
-  then
-    echo "SUCCESS. All backups have valid control data"
-  else
-    echo "FAIL. Some backups have invalid controld data"
-    return 1
-  fi
+  check_control_data
 }
 
 check_wal_archive() {
+  local NODE="$1"
   local RESULT
   local EXIT_CODE
   try_function wait_until try_check_wal_archive "$NODE"
@@ -86,7 +75,7 @@ check_timelines(){
   local CUSTOM_COLUMNS=NAME:.metadata.name,PHASE:.status.process.status,WAL_FILE:.status.backupInformation.startWalFile,TIMELINE:.status.backupInformation.timeline
   BACKUP_LINE="$(kubectl get sgbackup -n "$CLUSTER_NAMESPACE" \
     -o custom-columns="$CUSTOM_COLUMNS" \
-    | tail -n +2 | sed 's/\s\+/ /g' | grep "Completed")"
+    | tail -n 1 | sed 's/\s\+/ /g' | grep "Completed")"
 
   EXPECTED_TIMELINE="$(echo "$BACKUP_LINE" | cut -d ' ' -f 3)"
   EXPECTED_TIMELINE="$(printf "%d" 0x$(expr substr "$EXPECTED_TIMELINE" 1 8))"
@@ -108,22 +97,20 @@ check_control_data(){
   EXPECTED_CONTROL_DATA_LENGTH="$(kubectl exec -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME-0" -c patroni \
     -- bash -c 'pg_controldata --pgdata=$PG_DATA_PATH' | wc -l)"
   kubectl get sgbackup -n "$CLUSTER_NAMESPACE" -o custom-columns="$CUSTOM_COLUMNS" \
-    | tail -n +2 | grep "Completed" | awk '{print $1}' | while read BACKUP_NAME
-    do
-      local ACTUAL_CONTROL_DATA_LENGTH
-      ACTUAL_CONTROL_DATA_LENGTH="$(kubectl get sgbackup -n "$CLUSTER_NAMESPACE" "$BACKUP_NAME" -o json \
-        | jq '.status.backupInformation.controlData | length')"
-
-      if [ "$EXPECTED_CONTROL_DATA_LENGTH" != "$ACTUAL_CONTROL_DATA_LENGTH" ]
-      then
-        echo "FAIL. Backup $BACKUP_NAME has invalid controlData. Expected $EXPECTED_CONTROL_DATA_LENGTH fields, found $ACTUAL_CONTROL_DATA_LENGTH"
-        return 1
-      else
-        echo "Backup $BACKUP_NAME has valid controlData"
-      fi
-
-    done
-
+    | tail -n +2 | grep "Completed" | awk '{print $1}' \
+    | while read -r BACKUP_NAME
+      do
+        local ACTUAL_CONTROL_DATA_LENGTH
+        ACTUAL_CONTROL_DATA_LENGTH="$(kubectl get sgbackup -n "$CLUSTER_NAMESPACE" "$BACKUP_NAME" -o json \
+          | jq '.status.backupInformation.controlData | length')"
+        if [ "$EXPECTED_CONTROL_DATA_LENGTH" != "$ACTUAL_CONTROL_DATA_LENGTH" ]
+        then
+          echo "FAIL. Backup $BACKUP_NAME has invalid controlData. Expected $EXPECTED_CONTROL_DATA_LENGTH fields, found $ACTUAL_CONTROL_DATA_LENGTH"
+          return 1
+        else
+          echo "Backup $BACKUP_NAME has valid controlData"
+        fi
+      done
 }
 
 check_automatic_backup_cr() {
@@ -159,12 +146,21 @@ check_manual_backup() {
   BACKUP_2_NAME="$(get_sgbackup_name "${CLUSTER_NAME}-${NODE}-$(shuf -i 0-65535 -n 1)-2")"
   local BACKUP_3_NAME
   BACKUP_3_NAME="$(get_sgbackup_name "${CLUSTER_NAME}-${NODE}-$(shuf -i 0-65535 -n 1)-3")"
+
+  check_manual_backup_only "$NODE" "$BACKUP_NAME"
+
+  check_backup_default_annotations "$BACKUP_NAME"
+
+  check_backup_managed_lifecycle "$NODE" "$BACKUP_NAME" "$BACKUP_2_NAME"
+
+  check_backup_retention_and_deletion "$NODE" "$BACKUP_NAME" "$BACKUP_2_NAME" "$BACKUP_3_NAME"
+}
+
+check_manual_backup_only() {
+  local NODE="$1"
+  local BACKUP_NAME="$2"
   local ACTUAL_BACKUP_NAME
   local CUSTOM_COLUMNS=BACKUP_NAME:.status.internalName,PHASE:.status.process.status,HOSTNAME:.status.backupInformation.sourcePod
-
-  # Avoid automatic backups while testing manual backups
-  kubectl patch sgbackupconfig -n "$CLUSTER_NAMESPACE" backupconf --type json \
-    --patch '[{"op":"replace","path":"/spec/baseBackups/cronSchedule","value":"0 5 31 2 *"}]'
 
   kubectl delete sgbackup -n "$CLUSTER_NAMESPACE" --all
 
@@ -208,16 +204,10 @@ check_manual_backup() {
     echo "FAIL. The full backup of created CR is not available"
     return 1
   fi
+}
 
-  check_is_managed_lifecycle_value false
-
-  kubectl patch sgbackup -n "$CLUSTER_NAMESPACE" "$BACKUP_NAME" --type json \
-    --patch '[{"op":"replace","path":"/spec/managedLifecycle","value":true}]'
-
-  create_backup "$BACKUP_2_NAME" true
-
-  wait_until check_is_managed_lifecycle_value true
-
+check_backup_default_annotations() {
+  local BACKUP_NAME="$1"
   local DEFAULT_ANNOTATION
   DEFAULT_ANNOTATION="$(kubectl get sgbackup -n "$CLUSTER_NAMESPACE" "$BACKUP_NAME" -o json | jq '.metadata.annotations["stackgres.io/operatorVersion"]')"
 
@@ -227,6 +217,39 @@ check_manual_backup() {
     return 1
   else
     echo "SUCCESS. Defaults annotations created"
+  fi
+}
+
+check_backup_managed_lifecycle() {
+  local NODE="$1"
+  local BACKUP_NAME="$2"
+  local BACKUP_2_NAME="$3"
+  check_is_managed_lifecycle_value "$NODE" "$BACKUP_NAME" false
+
+  kubectl patch sgbackup -n "$CLUSTER_NAMESPACE" "$BACKUP_NAME" --type json \
+    --patch '[{"op":"replace","path":"/spec/managedLifecycle","value":true}]'
+
+  create_backup "$BACKUP_2_NAME" true
+
+  wait_until check_is_managed_lifecycle_value "$NODE" "$BACKUP_NAME" true
+}
+
+check_backup_retention_and_deletion() {
+  local NODE="$1"
+  local BACKUP_NAME="$2"
+  local BACKUP_2_NAME="$3"
+  local BACKUP_3_NAME="$4"
+  local CUSTOM_COLUMNS=BACKUP_NAME:.status.internalName,PHASE:.status.process.status,HOSTNAME:.status.backupInformation.sourcePod
+  local ACTUAL_BACKUP_NAME
+
+  ACTUAL_BACKUP_NAME="$(kubectl get sgbackup -n "$CLUSTER_NAMESPACE" "$BACKUP_NAME" \
+    -o custom-columns="$CUSTOM_COLUMNS" \
+    | tail -n +2 | grep " Completed   ${CLUSTER_NAME}-${NODE}$" | tail -n 1 | cut -d ' ' -f 1)"
+
+  if [ -z "$ACTUAL_BACKUP_NAME" ]
+  then
+    echo "FAIL. Backup name not found"
+    return 1
   fi
 
   create_backup "$BACKUP_3_NAME" true
@@ -249,10 +272,6 @@ check_manual_backup() {
 
   kubectl delete sgbackup -n "$CLUSTER_NAMESPACE" "$BACKUP_2_NAME"
   kubectl delete sgbackup -n "$CLUSTER_NAMESPACE" "$BACKUP_3_NAME"
-
-  # Avoid automatic backups while testing manual backups
-  kubectl patch sgbackupconfig -n "$CLUSTER_NAMESPACE" backupconf --type json \
-    --patch '[{"op":"replace","path":"/spec/baseBackups/cronSchedule","value":"*/1 * * * *"}]'
 
   if wait_until eval '[ "$(kubectl exec -n "$CLUSTER_NAMESPACE" "${CLUSTER_NAME}-${NODE}" -c patroni -- \
       exec-with-env backup -- wal-g backup-list | grep "^$ACTUAL_BACKUP_NAME " | wc -l)" -eq 0 ]'
@@ -278,18 +297,21 @@ EOF
 }
 
 check_is_managed_lifecycle_value() {
+  local NODE="$1"
+  local BACKUP_NAME="$2"
+  local EXPECTED_MANAGED_LIFECYCLE="$3"
   local CUSTOM_COLUMNS=MANAGED_LYFECYCLE:.status.process.managedLifecycle,PHASE:.status.process.status,HOSTNAME:.status.backupInformation.sourcePod
   local ACTUAL_MANAGED_LYFECYCLE
   ACTUAL_MANAGED_LYFECYCLE="$(kubectl get sgbackup -n "$CLUSTER_NAMESPACE" "$BACKUP_NAME" \
     -o custom-columns="$CUSTOM_COLUMNS" \
     | tail -n +2 | grep " Completed   ${CLUSTER_NAME}-${NODE}$" | tail -n 1 | cut -d ' ' -f 1)"
 
-  if [ "$ACTUAL_MANAGED_LYFECYCLE" != "$1" ]
+  if [ "$ACTUAL_MANAGED_LYFECYCLE" != "$EXPECTED_MANAGED_LIFECYCLE" ]
   then
-    echo "FAIL. Backup /status/process/managedLifecycle expected to be $1 but was $ACTUAL_MANAGED_LYFECYCLE"
+    echo "FAIL. Backup /status/process/managedLifecycle expected to be $EXPECTED_MANAGED_LIFECYCLE but was $ACTUAL_MANAGED_LYFECYCLE"
     return 1
   else
-    echo "SUCCESS. Backup /status/process/managedLifecycle was $1"
+    echo "SUCCESS. Backup /status/process/managedLifecycle was $EXPECTED_MANAGED_LIFECYCLE"
   fi
 }
 
@@ -335,7 +357,7 @@ get_completed_backup_count() {
 }
 
 check_single_backup_job() {
-  if ! wait_until -t 60 -i 1 eval '[ "$(get_manual_backup_pod_count)" -gt 0 ]'
+  if ! wait_until -t 60 -i 1 eval '[ "$(get_backup_pod_count)" -gt 0 ]'
   then
     echo "Good. Only 1 running backup job"
   else
@@ -344,7 +366,7 @@ check_single_backup_job() {
   fi
 }
 
-get_manual_backup_pod_count() {
+get_backup_pod_count() {
   kubectl get pod -n "$CLUSTER_NAMESPACE" -l backup=true \
     --template '{{ range .items }}{{ printf "%s %s\n" .metadata.ownerReferences .metadata.labels }}{{ end }}' \
     | grep ' kind:Job ' | wc -l
