e2e: allow to skip postgis extension installation if not available

diff --git a/stackgres-k8s/e2e/spec/abstract/dbops-major-version-upgrade b/stackgres-k8s/e2e/spec/abstract/dbops-major-version-upgrade
--- a/stackgres-k8s/e2e/spec/abstract/dbops-major-version-upgrade
+++ b/stackgres-k8s/e2e/spec/abstract/dbops-major-version-upgrade
@@ -8,6 +8,8 @@ e2e_test_install() {
   CLUSTER_NAME="$(get_sgcluster_name dbops-major-version-upgrade)"
   DBOPS_NAME="$(get_sgdbops_name major-version-upgrade)"
 
+  POSTGIS_VERSION="$(get_latest_version_of_extension postgis 12 || true)"
+
   kubectl create namespace "$CLUSTER_NAMESPACE"
 
   deploy_curl_pod "$CLUSTER_NAMESPACE"
@@ -23,20 +25,32 @@ reset_cluster() {
 
   wait_until eval '[ "$(kubectl get pvc -n "$CLUSTER_NAMESPACE" --template "{{ .items | len }}")" = 0 ]'
 
-  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" 2 \
-    --set-string cluster.postgres.version="$E2E_MAJOR_SOURCE_POSTGRES_VERSION" \
-    --set-string cluster.postgres.extensions[0].name=postgis \
-    "$@"
+  if [ -n "$POSTGIS_VERSION" ]
+  then
+    create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" 2 \
+      --set-string cluster.postgres.version="$E2E_MAJOR_SOURCE_POSTGRES_VERSION" \
+      --set-string cluster.postgres.extensions[0].name=postgis \
+      --set-string cluster.postgres.extensions[0].version="$POSTGIS_VERSION" \
+      "$@"
+  else
+    echo "Extension postgis not found for $(uname -m)"
+    create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" 2 \
+      --set-string cluster.postgres.version="$E2E_MAJOR_SOURCE_POSTGRES_VERSION" \
+      "$@"
+  fi
 
   wait_pods_running "$CLUSTER_NAMESPACE" "$PODS_RUNNING"
   wait_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE"
 
-  kubectl exec -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-0 -c postgres-util -- psql -c "$(cat << 'EOF'
+  if [ -n "$POSTGIS_VERSION" ]
+  then
+    kubectl exec -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-0 -c postgres-util -- psql -c "$(cat << 'EOF'
 CREATE EXTENSION postgis;
 CREATE MATERIALIZED VIEW test AS
  SELECT 'mpoint_7', ST_AsEWKT(ST_GeomFromGML('<gml:MultiPoint srsName="EPSG:27582"><gml:pointMember><gml:Point><gml:coordinates>1,2</gml:coordinates></gml:Point></gml:pointMember><gml:pointMember><gml:Point srsName="EPSG:27562"><gml:coordinates>400000,5000000</gml:coordinates></gml:Point></gml:pointMember></gml:MultiPoint>'));
 EOF
-    )"
+      )"
+  fi
 
   create_or_replace_cluster "$CLUSTER_NAME-for-major-version-upgrade" "$CLUSTER_NAMESPACE" 1 \
     --set cluster.create=false \
