version: 1.9.0-SNAPSHOT

diff --git a/stackgres-k8s/e2e/spec/previous/1.8/spec/dbops-major-version-upgrade b/stackgres-k8s/e2e/spec/previous/1.8/spec/dbops-major-version-upgrade
--- a/stackgres-k8s/e2e/spec/previous/1.8/spec/dbops-major-version-upgrade
+++ b/stackgres-k8s/e2e/spec/previous/1.8/spec/dbops-major-version-upgrade
@@ -12,7 +12,7 @@ e2e_test() {
 
   run_test "Checking that major version upgrade check is working" check_major_version_upgrade_check_is_working
 
-  run_test "Checking that major version upgrade fail on missing extension version" check_major_version_upgrade_fail_on_missing_extension_version
+  run_test "Checking that major version upgrade creation fails on missing extension version" check_major_version_upgrade_creation_fail_on_missing_extension_version
 }
 
 check_major_version_upgrade_is_working() {
@@ -49,7 +49,8 @@ EOF
     --set-string cluster.postgres.version="$E2E_MAJOR_SOURCE_POSTGRES_VERSION" \
     --set cluster.configurations.backups.retention=2 \
     --set-string cluster.configurations.backups.cronSchedule='0 5 31 2 *' \
-    --set-string cluster.configurations.backups.sgObjectStorage=backupconf
+    --set-string cluster.configurations.backups.sgObjectStorage=backupconf \
+    --set cluster.postgres.ssl.enabled=true
 
   local BACKUP_NAME_PRE BACKUP_NAME_POST
   BACKUP_NAME_PRE="$(get_sgbackup_name "$CLUSTER_NAME-pre")"
@@ -168,12 +169,15 @@ EOF
   kubectl delete sgdbops -n "$CLUSTER_NAMESPACE" "$DBOPS_NAME"
 }
 
-check_major_version_upgrade_fail_on_missing_extension_version() {
+check_major_version_upgrade_creation_fail_on_missing_extension_version() {
   local E2E_MAJOR_SOURCE_POSTGRES_VERSION=14
-  local E2E_MAJOR_TARGET_POSTGRES_VERSION=15.2
+  local E2E_MAJOR_TARGET_POSTGRES_VERSION=15
+  local SOURCE_PG_REPACK_VERSION
+  SOURCE_PG_REPACK_VERSION="$(get_oldest_version_of_extension pg_repack "${E2E_MAJOR_SOURCE_POSTGRES_VERSION%.*}")"
+
   reset_cluster_only_pg_repack
 
-  cat << EOF | kubectl create -f -
+  cat << EOF > "$LOG_PATH"/failing-dbops.yaml
 apiVersion: stackgres.io/v1
 kind: SGDbOps
 metadata:
@@ -186,10 +190,13 @@ spec:
     postgresVersion: "$E2E_MAJOR_TARGET_POSTGRES_VERSION"
     sgPostgresConfig: postgresconf-for-major-version-upgrade
     check: true
-    postgresExtensions:
-    - name: pg_repack
-      version: $TARGET_PG_REPACK_VERSION
 EOF
 
-  assert_dbops_failure "$DBOPS_NAME" "$CLUSTER_NAMESPACE" "$E2E_TIMEOUT"
+  if ! kubectl create -f "$LOG_PATH"/failing-dbops.yaml
+  then
+    echo "SUCCESS. The SGDbOps creation has failed"
+  else
+    echo "FAIL. The SGDbOps creation has not failed"
+    return 1
+  fi
 }
