fix: operator upgrade should work

diff --git a/stackgres-k8s/install/operator-sdk/stackgres-operator/config/manager/manager.template.yaml b/stackgres-k8s/install/operator-sdk/stackgres-operator/config/manager/manager.template.yaml
--- a/stackgres-k8s/install/operator-sdk/stackgres-operator/config/manager/manager.template.yaml
+++ b/stackgres-k8s/install/operator-sdk/stackgres-operator/config/manager/manager.template.yaml
@@ -2,8 +2,7 @@ apiVersion: v1
 kind: Namespace
 metadata:
   labels:
-    app: stackgres-operator
-    control-plane: stackgres-controller-manager
+    app: stackgres-helm-controller-manager
     app.kubernetes.io/name: namespace
     app.kubernetes.io/instance: system
     app.kubernetes.io/component: manager
@@ -15,11 +14,10 @@ metadata:
 apiVersion: apps/v1
 kind: Deployment
 metadata:
-  name: controller-manager
+  name: helm-controller-manager
   namespace: system
   labels:
-    app: stackgres-operator
-    control-plane: stackgres-controller-manager
+    app: stackgres-helm-controller-manager
     app.kubernetes.io/name: deployment
     app.kubernetes.io/instance: controller-manager
     app.kubernetes.io/component: manager
@@ -29,16 +27,14 @@ metadata:
 spec:
   selector:
     matchLabels:
-      app: stackgres-operator
-      control-plane: stackgres-controller-manager
+      app: stackgres-helm-controller-manager
   replicas: 1
   template:
     metadata:
       annotations:
         kubectl.kubernetes.io/default-container: manager
       labels:
-        app: stackgres-operator
-        control-plane: stackgres-controller-manager
+        app: stackgres-helm-controller-manager
     spec:
       affinity:
         nodeAffinity:
@@ -99,48 +95,79 @@ spec:
       initContainers:
       - command:
         - sh
-        - -ec
+        - -exc
         - |
+          # TODO: Remove this as soon as version 1.4 get out of support!
+          PREVIOUS_SGCONFIG="$(kubectl get sgconfig stackgres -o yaml || true)"
+          if [ "x" = "x$SGCONFIG" ] \
+            && [ "x" != "x$PREVIOUS_SGCONFIG" ]
+          then
+            SGCONFIG="$PREVIOUS_SGCONFIG"
+          fi
+
+          SGCONFIG_SPEC=""
+          if [ "x" != "x$SGCONFIG" ]
+          then
+            if ! SGCONFIG="$(printf %s "$SGCONFIG" | kubectl create -f - --dry-run=client -o yaml)"
+            then
+              printf "Please set a correct value for SGCONFIG env var in Subscription since the following is invalid:\n\n%s\n" "$SGCONFIG"
+              exit 1
+            fi
+            if printf %s "$SGCONFIG" | grep -q '^spec:$'
+            then
+              echo "Found SGConfig spec"
+              SGCONFIG_SPEC_LINE="\$(printf %s "\$SGCONFIG" \
+                | grep -n '^spec:$' | cut -d : -f 1)"
+              SGCONFIG_AFTER_SPEC_LINE="\$(printf %s "\$SGCONFIG" \
+                | tail -n +"\$((SGCONFIG_SPEC_LINE + 1))" \
+                | grep -n '^[^ #].*$' | cut -d : -f 1)"
+              if [ x != "x$SGCONFIG_AFTER_SPEC_LINE" ]
+              then
+                SGCONFIG_SPEC="\$(printf %s "\$SGCONFIG" \
+                  | head -n "\$((SGCONFIG_SPEC_LINE + SGCONFIG_AFTER_SPEC_LINE - 1))" \
+                  | tail -n +"\$((SGCONFIG_AFTER_SPEC_LINE - 1))")"
+              else
+                SGCONFIG_SPEC="\$(printf %s "\$SGCONFIG" \
+                  | tail -n +"\$((SGCONFIG_SPEC_LINE + 1))")"
+              fi
+            else
+              echo "Found SGConfig without spec, ignoring!"
+            fi
+          fi
+
           OPERATOR_NAME="\$(kubectl get operators.operators.coreos.com -o name \
             | grep '^operator.operators.coreos.com/stackgres' \
             | head -n 1 | cut -d / -f 2)"
           test -n "\$OPERATOR_NAME"
           OPERATOR_UID="\$(kubectl get operators.operators.coreos.com "\$OPERATOR_NAME" --template '{{ .metadata.uid }}')"
           test -n "\$OPERATOR_UID"
-          PREVIOUS_SGCONFIG_NAME="\$(kubectl get sgconfig -o name | cut -d / -f 2)"
-          PREVIOUS_SGCONFIG_SPEC=""
-          if [ "\$PREVIOUS_SGCONFIG_NAME" != stackgres-operator ] \
-            && kubectl get sgconfig "\$PREVIOUS_SGCONFIG_NAME" -o yaml | grep -q '^spec:\$' \
-            && kubectl get sgconfig "\$PREVIOUS_SGCONFIG_NAME" -o yaml | grep -q '^status:\$'
-          then
-            # TODO: Remove this as soon as version 1.4 get out of support!
-            PREVIOUS_SGCONFIG="\$(kubectl get sgconfig "\$PREVIOUS_SGCONFIG_NAME" -o yaml)"
-            PREVIOUS_SGCONFIG_SPEC_LINE="\$(printf %s "\$PREVIOUS_SGCONFIG" \
-              | grep -n '^spec:\$' | cut -d : -f 1)"
-            PREVIOUS_SGCONFIG_STATUS_LINE="\$(printf %s "\$PREVIOUS_SGCONFIG" \
-              | grep -n '^status:\$' | cut -d : -f 1)"
-            PREVIOUS_SGCONFIG_SPEC="\$(printf %s "\$PREVIOUS_SGCONFIG" \
-              | head -n "\$((PREVIOUS_SGCONFIG_STATUS_LINE - 1))" \
-              | tail -n +"\$((PREVIOUS_SGCONFIG_SPEC_LINE + 1))")"
-            kubectl delete sgconfig "\$PREVIOUS_SGCONFIG_NAME"
-            kubectl delete clusterrole -l "meta.helm.sh/release-name=\$PREVIOUS_SGCONFIG_NAME"
-            kubectl delete clusterrolebinding -l "meta.helm.sh/release-name=\$PREVIOUS_SGCONFIG_NAME"
-            kubectl delete validatingwebhookconfiguration -l "meta.helm.sh/release-name=\$PREVIOUS_SGCONFIG_NAME"
-            kubectl delete mutatingwebhookconfiguration -l "meta.helm.sh/release-name=\$PREVIOUS_SGCONFIG_NAME"
-          fi
+
           cat << EOF | kubectl apply -f -
           apiVersion: stackgres.io/v1
           kind: SGConfig
           metadata:
             name: stackgres-operator
           spec:
+          \$SGCONFIG_SPEC
             clusterOwnerReferences:
             - apiVersion: operators.coreos.com/v1
               kind: Operator
               name: \$OPERATOR_NAME
               uid: \$OPERATOR_UID
-          \$PREVIOUS_SGCONFIG_SPEC
           EOF
+
+          # TODO: Remove this as soon as version 1.4 get out of support!
+          kubectl delete --ignore-not-found sgconfig stackgres
+          kubectl delete --ignore-not-found clusterrole stackgres
+          kubectl delete --ignore-not-found clusterrole stackgres-restapi
+          kubectl delete --ignore-not-found clusterrolebinding stackgres
+          kubectl delete --ignore-not-found clusterrolebinding stackgres-restapi
+          kubectl delete --ignore-not-found clusterrolebinding stackgres-restapi-admin
+          kubectl delete --ignore-not-found validatingwebhookconfiguration stackgres
+          kubectl delete --ignore-not-found mutatingwebhookconfiguration stackgres
+          kubectl delete --ignore-not-found secret stackgres-certs
+          kubectl delete --ignore-not-found secret stackgres-web-certs
+          kubectl wait sgconfig stackgres-operator --for condition=Deployed
         image: ongres/kubectl:v1.25.5-build-6.19
         imagePullPolicy: IfNotPresent
         name: default
@@ -168,5 +195,5 @@ fi
           requests:
             cpu: 10m
             memory: 128Mi
-      serviceAccountName: controller-manager
+      serviceAccountName: helm-controller-manager
       terminationGracePeriodSeconds: 10
