fix: operator upgrade should work

diff --git a/stackgres-k8s/install/operator-sdk/stackgres-operator/config/manager/manager.template.yaml b/stackgres-k8s/install/operator-sdk/stackgres-operator/config/manager/manager.template.yaml
--- a/stackgres-k8s/install/operator-sdk/stackgres-operator/config/manager/manager.template.yaml
+++ b/stackgres-k8s/install/operator-sdk/stackgres-operator/config/manager/manager.template.yaml
@@ -92,28 +92,27 @@ spec:
           requests:
             cpu: 10m
             memory: 128Mi
-      initContainers:
       - command:
         - sh
         - -exc
         - |
           # TODO: Remove this as soon as version 1.4 get out of support!
-          PREVIOUS_SGCONFIG="$(kubectl get sgconfig stackgres -o yaml || true)"
-          if [ "x" = "x$SGCONFIG" ] \
-            && [ "x" != "x$PREVIOUS_SGCONFIG" ]
+          PREVIOUS_SGCONFIG="\$(kubectl get sgconfig stackgres -o yaml || true)"
+          if [ "x" = "x\$SGCONFIG" ] \
+            && [ "x" != "x\$PREVIOUS_SGCONFIG" ]
           then
-            SGCONFIG="$PREVIOUS_SGCONFIG"
+            SGCONFIG="\$PREVIOUS_SGCONFIG"
           fi
 
           SGCONFIG_SPEC=""
-          if [ "x" != "x$SGCONFIG" ]
+          if [ "x" != "x\$SGCONFIG" ]
           then
-            if ! SGCONFIG="$(printf %s "$SGCONFIG" | kubectl create -f - --dry-run=client -o yaml)"
+            if ! SGCONFIG="\$(printf %s "\$SGCONFIG" | kubectl create -f - --dry-run=client -o yaml)"
             then
-              printf "Please set a correct value for SGCONFIG env var in Subscription since the following is invalid:\n\n%s\n" "$SGCONFIG"
+              printf "Please set a correct value for SGCONFIG env var in Subscription since the following is invalid:\n\n%s\n" "\$SGCONFIG"
               exit 1
             fi
-            if printf %s "$SGCONFIG" | grep -q '^spec:$'
+            if printf %s "\$SGCONFIG" | grep -q '^spec:$'
             then
               echo "Found SGConfig spec"
               SGCONFIG_SPEC_LINE="\$(printf %s "\$SGCONFIG" \
@@ -121,7 +120,7 @@ spec:
               SGCONFIG_AFTER_SPEC_LINE="\$(printf %s "\$SGCONFIG" \
                 | tail -n +"\$((SGCONFIG_SPEC_LINE + 1))" \
                 | grep -n '^[^ #].*$' | cut -d : -f 1)"
-              if [ x != "x$SGCONFIG_AFTER_SPEC_LINE" ]
+              if [ x != "x\$SGCONFIG_AFTER_SPEC_LINE" ]
               then
                 SGCONFIG_SPEC="\$(printf %s "\$SGCONFIG" \
                   | head -n "\$((SGCONFIG_SPEC_LINE + SGCONFIG_AFTER_SPEC_LINE - 1))" \
@@ -134,6 +133,19 @@ spec:
               echo "Found SGConfig without spec, ignoring!"
             fi
           fi
+
+          # TODO: Remove this as soon as version 1.4 get out of support!
+          kubectl delete --ignore-not-found sgconfig stackgres
+          kubectl delete --ignore-not-found clusterrole stackgres
+          kubectl delete --ignore-not-found clusterrole stackgres-restapi
+          kubectl delete --ignore-not-found clusterrolebinding stackgres
+          kubectl delete --ignore-not-found clusterrolebinding stackgres-restapi
+          kubectl delete --ignore-not-found clusterrolebinding stackgres-restapi-admin
+          kubectl delete --ignore-not-found validatingwebhookconfiguration stackgres
+          kubectl delete --ignore-not-found mutatingwebhookconfiguration stackgres
+          kubectl delete --ignore-not-found secret stackgres-certs
+          kubectl delete --ignore-not-found secret stackgres-web-certs
+          kubectl delete --ignore-not-found deployment -l olm.owner=stackgres.v1.4.3
 
           OPERATOR_NAME="\$(kubectl get operators.operators.coreos.com -o name \
             | grep '^operator.operators.coreos.com/stackgres' \
@@ -156,19 +168,8 @@ spec:
               uid: \$OPERATOR_UID
           EOF
 
-          # TODO: Remove this as soon as version 1.4 get out of support!
-          kubectl delete --ignore-not-found sgconfig stackgres
-          kubectl delete --ignore-not-found clusterrole stackgres
-          kubectl delete --ignore-not-found clusterrole stackgres-restapi
-          kubectl delete --ignore-not-found clusterrolebinding stackgres
-          kubectl delete --ignore-not-found clusterrolebinding stackgres-restapi
-          kubectl delete --ignore-not-found clusterrolebinding stackgres-restapi-admin
-          kubectl delete --ignore-not-found validatingwebhookconfiguration stackgres
-          kubectl delete --ignore-not-found mutatingwebhookconfiguration stackgres
-          kubectl delete --ignore-not-found secret stackgres-certs
-          kubectl delete --ignore-not-found secret stackgres-web-certs
-          kubectl wait sgconfig stackgres-operator --for condition=Deployed
-        image: ongres/kubectl:v1.25.5-build-6.19
+          while true; do sleep 3600; done
+        image: quay.io/ongres/kubectl:v1.25.5-build-6.19
         imagePullPolicy: IfNotPresent
         name: default
         securityContext:
@@ -194,6 +195,6 @@ fi
             memory: 512Mi
           requests:
             cpu: 10m
-            memory: 128Mi
+            memory: 8Mi
       serviceAccountName: helm-controller-manager
       terminationGracePeriodSeconds: 10
