version: 1.13.0-SNAPSHOT

diff --git a/stackgres-k8s/e2e/spec/previous/1.12/spec/operator-olm b/stackgres-k8s/e2e/spec/previous/1.12/spec/operator-olm
--- a/stackgres-k8s/e2e/spec/previous/1.12/spec/operator-olm
+++ b/stackgres-k8s/e2e/spec/previous/1.12/spec/operator-olm
@@ -42,10 +42,22 @@ e2e_test() {
 
   run_test "Namespace endpoint should return all kubernetes namespaces" check_namespace
 
-  run_test "Check that operator can be deleted" check_operator_delete
+  if [ "$E2E_SKIP_CHECK_OPERATOR_DELETE" = true ]
+  then
+    echo "Skip operator deletion check"
+  else
+    run_test "Check that operator can be deleted" check_operator_delete
+  fi
 }
 
 check_operator_install() {
+  SGCONFIG_NAMESPACE="$OPERATOR_NAMESPACE"
+  if [ "x$E2E_ALLOWED_NAMESPACES" != x ] \
+    && ! printf ' %s ' "$E2E_ALLOWED_NAMESPACES" | grep -qF " $OPERATOR_NAMESPACE "
+  then
+    SGCONFIG_NAMESPACE="$CLUSTER_NAMESPACE"
+  fi
+
   install_operator_olm
 
   check_operator_installed
@@ -59,8 +71,144 @@ kind: OperatorGroup
 metadata:
   name: stackgres
   namespace: $OPERATOR_NAMESPACE
+spec:
+$(
+  if [ "x$E2E_ALLOWED_NAMESPACES" != x ]
+  then
+    cat << INNER_EOF
+  targetNamespaces:
+$(printf %s "$E2E_ALLOWED_NAMESPACES" | tr ' ' '\n' | sed 's/^/  - /')
+INNER_EOF
+  fi
+)
 EOF
   kubectl create -f "$LOG_PATH/stackgres-operator-group.yaml"
+
+  cat << EOF > "$LOG_PATH/sgconfig-patch.yaml"
+apiVersion: stackgres.io/v1
+kind: SGConfig
+spec:
+  operator:
+    image:
+      tag: "$IMAGE_TAG"
+  restapi:
+    image:
+      tag: "$IMAGE_TAG"
+  adminui:
+    image:
+      tag: "$ADMINUI_IMAGE_TAG"
+  jobs:
+    image:
+      tag: "$IMAGE_TAG"
+  developer:
+    version: $STACKGRES_VERSION
+$(
+  if [ -n "$E2E_EXTRA_MOUNT_BUILD_PATH" ]
+  then
+    cat << INNER_EOF
+    patches:
+      restapi:
+        volumes:
+          - name: app
+            hostPath:
+              path: "$(realpath "$E2E_EXTRA_MOUNT_BUILD_PATH"/stackgres-k8s/src/api-web/target/quarkus-app)"
+        volumeMounts:
+          - name: app
+            mountPath: /app/app
+            subPath: app
+          - name: app
+            mountPath: /app/lib
+            subPath: lib
+          - name: app
+            mountPath: /app/quarkus
+            subPath: quarkus
+          - name: app
+            mountPath: /app/quarkus-run.jar
+            subPath: quarkus-run.jar
+      adminui:
+        volumes:
+          - name: admin
+            hostPath:
+              path: "$(realpath "$E2E_EXTRA_MOUNT_BUILD_PATH"/stackgres-k8s/src/admin-ui/target/public)"
+        volumeMounts:
+          - name: admin
+            mountPath: /opt/app-root/src/admin
+      jobs:
+        volumes:
+          - name: app
+            hostPath:
+              path: "$(realpath "$E2E_EXTRA_MOUNT_BUILD_PATH"/stackgres-k8s/src/jobs/target/quarkus-app)"
+        volumeMounts:
+          - name: app
+            mountPath: /app/app
+            subPath: app
+          - name: app
+            mountPath: /app/lib
+            subPath: lib
+          - name: app
+            mountPath: /app/quarkus
+            subPath: quarkus
+          - name: app
+            mountPath: /app/quarkus-run.jar
+            subPath: quarkus-run.jar
+      clusterController:
+        volumes:
+          - name: app
+            hostPath:
+              path: "$(realpath "$E2E_EXTRA_MOUNT_BUILD_PATH"/stackgres-k8s/src/cluster-controller/target/quarkus-app)"
+        volumeMounts:
+          - name: app
+            mountPath: /app/app
+            subPath: app
+          - name: app
+            mountPath: /app/lib
+            subPath: lib
+          - name: app
+            mountPath: /app/quarkus
+            subPath: quarkus
+          - name: app
+            mountPath: /app/quarkus-run.jar
+            subPath: quarkus-run.jar
+      distributedlogsController:
+        volumes:
+          - name: app
+            hostPath:
+              path: "$(realpath "$E2E_EXTRA_MOUNT_BUILD_PATH"/stackgres-k8s/src/distributedlogs-controller/target/quarkus-app)"
+        volumeMounts:
+          - name: app
+            mountPath: /app/app
+            subPath: app
+          - name: app
+            mountPath: /app/lib
+            subPath: lib
+          - name: app
+            mountPath: /app/quarkus
+            subPath: quarkus
+          - name: app
+            mountPath: /app/quarkus-run.jar
+            subPath: quarkus-run.jar
+INNER_EOF
+  fi
+)
+EOF
+
+  EXTRA_OPTS="$(printf %s "
+        -Dquarkus.log.category.\"io.stackgres\".level=DEBUG 
+        -Dquarkus.log.category.\"io.quarkus\".level=INFO 
+        -Dquarkus.log.category.\"io.stackgres.dbops\".level=TRACE 
+        -Dquarkus.log.category.\"io.stackgres.backup\".level=TRACE 
+        -Dquarkus.log.category.\"io.stackgres.wal-g\".level=INFO 
+        -Dquarkus.log.category.\"io.stackgres.patroni\".level=TRACE 
+        -Dquarkus.log.category.\"io.stackgres.fluent-bit\".level=TRACE 
+        -Dquarkus.log.category.\"io.stackgres.fluentd\".level=TRACE 
+        -Dquarkus.log.category.\"io.stackgres.prometheus-postgres-exporter\".level=TRACE 
+        -Dquarkus.log.category.\"okhttp3.logging.HttpLoggingInterceptor\".level=$(
+          # shellcheck disable=SC2015
+          [ "$E2E_LOG_OPERATOR_HTTP" = true ] && echo TRACE || echo INFO) 
+        -Dquarkus.log.category.\"stackgres-extensions-cache\".level=DEBUG 
+        -Dquarkus.log.category.\"io.stackgres.operator.conciliation\".level=TRACE 
+    " | tr -s ' \n' ' ' | jq -s -R .)"
+
   cat << EOF > "$LOG_PATH/stackgres-subscription-$STACKGRES_VERSION.yaml"
 apiVersion: operators.coreos.com/v1alpha1
 kind: Subscription
@@ -74,12 +222,53 @@ spec:
   sourceNamespace: $OPERATOR_NAMESPACE
   installPlanApproval: Manual
   startingCSV: stackgres.v$BUNDLE_STACKGRES_VERSION
+  config:
+    resources: {}
+    env: [
+      $E2E_OPERATOR_BUNDLE_EXTRA_ENV_JSON
+      {"name":"SG_IMAGE_CLUSTER_CONTROLLER","value":"${CLUSTER_CONTROLLER_IMAGE_NAME}"},
+      {"name":"SG_IMAGE_DISTRIBUTEDLOGS_CONTROLLER","value":"${DISTRIBUTEDLOGS_CONTROLLER_IMAGE_NAME}"},
+      {"name":"JAVA_OPTS","value":$EXTRA_OPTS},
+      {"name":"APP_OPTS","value":$EXTRA_OPTS},
+      {"name":"SGCONFIG","value":$(yq --arg sgconfig "${E2E_OPERATOR_BUNDLE_SGCONFIG:-{\}}" '($sgconfig | fromjson) * . | tostring' "$LOG_PATH/sgconfig-patch.yaml")}
+      ,
+$(
+  if [ "x$E2E_ALLOWED_NAMESPACES" != x ] \
+    && ! printf ' %s ' "$E2E_ALLOWED_NAMESPACES" | grep -qF " $OPERATOR_NAMESPACE "
+  then
+    cat << INNER_EOF
+      {"name":"SGCONFIG_NAMESPACE","value":"$CLUSTER_NAMESPACE"}
+INNER_EOF
+  fi
+)
+    ]
+$(
+  if [ -n "$E2E_EXTRA_MOUNT_BUILD_PATH" ]
+  then
+    cat << INNER_EOF
+  ,
+  volumes:[
+    {"name":"app","hostPath":{"path":"$(realpath "$E2E_EXTRA_MOUNT_BUILD_PATH"/stackgres-k8s/src/operator/target/quarkus-app)"}}],
+  volumeMounts:[
+    {"name":"app","mountPath":"/app/app","subPath":"app"},
+    {"name":"app","mountPath":"/app/lib","subPath":"lib"},
+    {"name":"app","mountPath":"/app/quarkus","subPath":"quarkus"},
+    {"name":"app","mountPath":"/app/quarkus-run.jar","subPath":"quarkus-run.jar"}]
+INNER_EOF
+  fi
+)
 EOF
   kubectl create -f "$LOG_PATH/stackgres-subscription-$STACKGRES_VERSION.yaml"
   INSTALL_PLAN="$(wait_until eval 'kubectl get installplan -n "$OPERATOR_NAMESPACE" -o json \
     | jq -r ".items[]|select(.status != null and (.spec.clusterServiceVersionNames[0] | gsub(\"-.*\";\"\")) == \"stackgres.v${BUNDLE_STACKGRES_VERSION%-*}\").metadata.name" \
     | grep .')"
   kubectl patch -n "$OPERATOR_NAMESPACE" installplan "$INSTALL_PLAN" --type merge -p '{"spec":{"approved":true}}'
+
+  wait_until eval 'kubectl get -n "$OPERATOR_NAMESPACE" deployment -l olm.owner="stackgres.v$BUNDLE_STACKGRES_VERSION" -o name | grep -q .'
+
+  wait_until -t "$((E2E_TIMEOUT * 3))" eval 'kubectl get pod -n "$OPERATOR_NAMESPACE" -l app=stackgres-operator -o name | wc -l | grep -xF 1'
+
+  wait_until kubectl rollout status --timeout=1s -n "$OPERATOR_NAMESPACE" deployment -l olm.owner="stackgres.v$BUNDLE_STACKGRES_VERSION"
 
   if ! wait_until eval 'kubectl get sgconfig -A -o name | wc -l | grep -qxF 1'
   then
@@ -89,9 +278,11 @@ EOF
     echo "SUCCESS. The StackGres SGConfig was found."
   fi
 
-  RELEASE_NAME="$(kubectl get sgconfig -n "$OPERATOR_NAMESPACE" -o name | grep "^sgconfig.stackgres.io/")"
+  wait_until eval 'kubectl get pod -n "$SGCONFIG_NAMESPACE" -l app=StackGresConfig,stackgres.io/restapi=true -o name | wc -l | grep -xF 1'
+
+  RELEASE_NAME="$(kubectl get sgconfig -n "$SGCONFIG_NAMESPACE" -o name | grep "^sgconfig.stackgres.io/")"
   RELEASE_NAME="${RELEASE_NAME#*/}"
-  kubectl patch -n "$OPERATOR_NAMESPACE" sgconfig "$RELEASE_NAME" --type merge \
+  kubectl patch -n "$SGCONFIG_NAMESPACE" sgconfig "$RELEASE_NAME" --type merge \
     -p '{"spec":{"grafana":{"autoEmbed": true, "webHost":"'"prometheus-grafana.$(prometheus_namespace)"'"}}}'
 }
 
@@ -104,7 +295,7 @@ check_operator_installed() {
     echo "SUCCESS. The StackGres operator service was available."
   fi
 
-  if ! wait_services_available "$OPERATOR_NAMESPACE" 1 "^stackgres-restapi$"
+  if ! wait_services_available "$SGCONFIG_NAMESPACE" 1 "^stackgres-restapi$"
   then
     echo "FAILED. The StackGres restapi service was not available."
     return 1
@@ -112,9 +303,17 @@ check_operator_installed() {
     echo "SUCCESS. The StackGres restapi service was available."
   fi
 
-  if [ "$(kubectl get sgconfig -n "$OPERATOR_NAMESPACE" stackgres-operator -o json | jq .spec.extensions.cache.enabled)" = true ]
+  if ! wait_until eval 'kubectl get job -n "$SGCONFIG_NAMESPACE" -l "app=StackGresConfig" -o name | wc -l | grep -qxF 0'
   then
-    if ! wait_services_available "$OPERATOR_NAMESPACE" 1 "^stackgres-operator-extensions-cache$"
+    echo "FAILED. The StackGres jobs still running."
+    return 1
+  else
+    echo "SUCCESS. The StackGres jobs all cleaned up."
+  fi
+
+  if [ "$(kubectl get sgconfig -n "$SGCONFIG_NAMESPACE" stackgres-operator -o json | jq .spec.extensions.cache.enabled)" = true ]
+  then
+    if ! wait_services_available "$SGCONFIG_NAMESPACE" 1 "^stackgres-operator-extensions-cache$"
     then
       echo "FAILED. The demo StackGres extensions cache service was not available."
       return 1
@@ -122,39 +321,20 @@ check_operator_installed() {
       echo "SUCCESS. The demo StackGres extensions cache service was available."
     fi
   fi
+
+  local PASSWORD
+  PASSWORD="$(kubectl get sgconfig -n "$SGCONFIG_NAMESPACE" stackgres-operator -o json \
+    | jq -r '.spec.authentication.password | select(. != null)' | tr -d '\n')"
+  if [ -n "$PASSWORD" ]
+  then
+    kubectl patch secret -n "$SGCONFIG_NAMESPACE" stackgres-restapi-admin -p '{"data":{"clearPassword":"'"$(printf '%s' "$PASSWORD" | base64)"'"}}'
+  fi
 }
 
 check_resources_creation() {
-  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" 1 \
-    --set cluster.create=false \
-    --set instanceProfiles[0].name=size-s \
-    --set instanceProfiles[0].cpu=125m \
-    --set instanceProfiles[0].memory=512Mi \
-    --set configurations.objectstorage.create=true \
-    --set-string cluster.configurations.backups.sgObjectStorage=backupconf \
-    --set-string cluster.configurations.backups.cronSchedule='0 5 31 2 *' \
-    --set cluster.configurations.backups.performance.maxDiskBandwidth=10485760 \
-    --set cluster.configurations.backups.performance.maxNetworkBandwidth=5242880 \
-    --set-string configurations.postgresconfig.postgresql\\.conf.max_connections=100 \
-    --set-string configurations.postgresconfig.postgresql\\.conf.invalid_param=true \
-    --set distributedLogs.enabled=true \
-    --set distributedLogs.create=true \
-    --set-string cluster.distributedLogs.sgDistributedLogs="$DISTRIBUTED_LOGS_NAME" \
-    --set-string distributedLogs.persistentVolume.size=128Mi
+  wait_until create_or_replace_distributed_logs
 
-  create_or_replace_cluster \
-    "$CLUSTER_1_NAME" "$CLUSTER_NAMESPACE" 1 \
-    --set configurations.create=false --set instanceProfiles=false \
-    --set-string cluster.sgInstanceProfile=size-s \
-    --set cluster.prometheusAutobind=true \
-    --set configurations.objectstorage.create=false \
-    --set-string cluster.configurations.backups.sgObjectStorage=backupconf \
-    --set-string cluster.configurations.backups.cronSchedule='0 5 31 2 *' \
-    --set cluster.configurations.backups.performance.maxDiskBandwidth=10485760 \
-    --set cluster.configurations.backups.performance.maxNetworkBandwidth=5242880 \
-    --set distributedLogs.enabled=true \
-    --set distributedLogs.create=false \
-    --set-string cluster.distributedLogs.sgDistributedLogs="$CLUSTER_NAMESPACE.$DISTRIBUTED_LOGS_NAME"
+  wait_until create_or_replace_cluster_with_backups
 
   deploy_curl_pod "$CLUSTER_NAMESPACE"
 
@@ -180,6 +360,51 @@ EOF
     --from-literal=script="CREATE DATABASE secret_managed_sql;"
   kubectl create configmap -n "$CLUSTER_NAMESPACE" configmap-script \
     --from-literal=script="CREATE DATABASE configmap_managed_sql;"
+  wait_until create_or_replace_cluster_from_backup
+
+  wait_pods_running "$CLUSTER_NAMESPACE" 4
+
+  wait_cluster "$CLUSTER_1_NAME" "$CLUSTER_NAMESPACE"
+
+  wait_cluster "$DISTRIBUTED_LOGS_NAME" "$CLUSTER_NAMESPACE"
+}
+
+create_or_replace_distributed_logs() {
+  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" 1 \
+    --set cluster.create=false \
+    --set instanceProfiles[0].name=size-s \
+    --set instanceProfiles[0].cpu=125m \
+    --set instanceProfiles[0].memory=512Mi \
+    --set configurations.objectstorage.create=true \
+    --set-string cluster.configurations.backups.sgObjectStorage=backupconf \
+    --set-string cluster.configurations.backups.cronSchedule='0 5 31 2 *' \
+    --set cluster.configurations.backups.performance.maxDiskBandwidth=10485760 \
+    --set cluster.configurations.backups.performance.maxNetworkBandwidth=5242880 \
+    --set-string configurations.postgresconfig.postgresql\\.conf.max_connections=100 \
+    --set-string configurations.postgresconfig.postgresql\\.conf.invalid_param=true \
+    --set distributedLogs.enabled=true \
+    --set distributedLogs.create=true \
+    --set-string cluster.distributedLogs.sgDistributedLogs="$DISTRIBUTED_LOGS_NAME" \
+    --set-string distributedLogs.persistentVolume.size=128Mi
+}
+
+create_or_replace_cluster_with_backups() {
+  create_or_replace_cluster \
+    "$CLUSTER_1_NAME" "$CLUSTER_NAMESPACE" 1 \
+    --set configurations.create=false --set instanceProfiles=false \
+    --set-string cluster.sgInstanceProfile=size-s \
+    --set cluster.prometheusAutobind=true \
+    --set configurations.objectstorage.create=false \
+    --set-string cluster.configurations.backups.sgObjectStorage=backupconf \
+    --set-string cluster.configurations.backups.cronSchedule='0 5 31 2 *' \
+    --set cluster.configurations.backups.performance.maxDiskBandwidth=10485760 \
+    --set cluster.configurations.backups.performance.maxNetworkBandwidth=5242880 \
+    --set distributedLogs.enabled=true \
+    --set distributedLogs.create=false \
+    --set-string cluster.distributedLogs.sgDistributedLogs="$CLUSTER_NAMESPACE.$DISTRIBUTED_LOGS_NAME"
+}
+
+create_or_replace_cluster_from_backup() {
   create_or_replace_cluster \
     "$CLUSTER_1_NAME" "$CLUSTER_NAMESPACE" 1 \
     --set configurations.create=false --set instanceProfiles=false \
@@ -203,23 +428,26 @@ EOF
     --set distributedLogs.enabled=true \
     --set distributedLogs.create=false \
     --set-string cluster.distributedLogs.sgDistributedLogs="$CLUSTER_NAMESPACE.$DISTRIBUTED_LOGS_NAME"
-
-  wait_pods_running "$CLUSTER_NAMESPACE" 4
-
-  wait_cluster "$CLUSTER_1_NAME" "$CLUSTER_NAMESPACE"
-
-  wait_cluster "$DISTRIBUTED_LOGS_NAME" "$CLUSTER_NAMESPACE"
 }
 
 check_operator_delete() {
+  SGCONFIG_NAMESPACE="$OPERATOR_NAMESPACE"
+  if [ "x$E2E_ALLOWED_NAMESPACES" != x ] \
+    && ! printf ' %s ' "$E2E_ALLOWED_NAMESPACES" | grep -qF " $OPERATOR_NAMESPACE "
+  then
+    SGCONFIG_NAMESPACE="$CLUSTER_NAMESPACE"
+  fi
+
   kubectl delete subscription -n "$OPERATOR_NAMESPACE" stackgres
+
+  kubectl delete clusterserviceversion -n "$OPERATOR_NAMESPACE" "stackgres.v$BUNDLE_STACKGRES_VERSION"
 
   check_operator_deleted
 }
 
 check_operator_deleted() {
-  if wait_until kubectl get service -n "$OPERATOR_NAMESPACE" | grep -c "^$RELEASE_NAME$" | grep -qxF 0 \
-    && wait_until kubectl get deployment -n "$OPERATOR_NAMESPACE" | grep -c "^$RELEASE_NAME$" | grep -qxF 0
+  if wait_until kubectl get service -n "$OPERATOR_NAMESPACE" -o name | grep -c "/$RELEASE_NAME$" | grep -qxF 0 \
+    && wait_until kubectl get deployment -n "$OPERATOR_NAMESPACE" -o name | grep -c "/$RELEASE_NAME$" | grep -qxF 0
   then
     echo "SUCCESS. The StackGres operator service was not available."
   else
@@ -227,22 +455,25 @@ check_operator_deleted() {
     return 1
   fi
 
-  if wait_until kubectl get service -n "$OPERATOR_NAMESPACE" | grep -c "^stackgres-restapi$" | grep -qxF 0 \
-    && wait_until kubectl get deployment -n "$OPERATOR_NAMESPACE" | grep -c "^stackgres-restapi$" | grep -qxF 0
+  if wait_until kubectl get service -n "$SGCONFIG_NAMESPACE" -o name | grep -c "/stackgres-restapi$" | grep -qxF 0 \
+    && wait_until kubectl get deployment -n "$SGCONFIG_NAMESPACE" -o name | grep -c "/stackgres-restapi$" | grep -qxF 0
   then
-    echo "SUCCESS. The StackGres restapi service was not available."
-  else
-    echo "FAILED. The StackGres restapi service was available."
+    echo "FAILED. The StackGres restapi service was not available."
     return 1
+  else
+    echo "SUCCESS. The StackGres restapi service was available."
   fi
 
-  if wait_until kubectl get service -n "$OPERATOR_NAMESPACE" | grep -c "^stackgres-operator-extensions-cache$" | grep -qxF 0 \
-    && wait_until kubectl get statefulset -n "$OPERATOR_NAMESPACE" | grep -c "^stackgres-operator-extensions-cache$" | grep -qxF 0
+  if [ "$(kubectl get sgconfig -n "$SGCONFIG_NAMESPACE" stackgres-operator -o json | jq .spec.extensions.cache.enabled)" = true ]
   then
-    echo "SUCCESS. The demo StackGres extensions cache service was not available."
-  else
-    echo "FAILED. The demo StackGres extensions cache service was available."
-    return 1
+    if wait_until kubectl get service -n "$SGCONFIG_NAMESPACE" -o name | grep -c "/stackgres-operator-extensions-cache$" | grep -qxF 0 \
+      && wait_until kubectl get statefulset -n "$SGCONFIG_NAMESPACE" -o name | grep -c "/stackgres-operator-extensions-cache$" | grep -qxF 0
+    then
+      echo "FAILED. The demo StackGres extensions cache service was not available."
+      return 1
+    else
+      echo "SUCCESS. The demo StackGres extensions cache service was available."
+    fi
   fi
 }
 
@@ -430,6 +661,8 @@ check_namespace() {
     return 0
   else
     echo "FAIL. Namespace endpoint not return all namespaces"
+    local RETURN EXIT_CODE
+    try_function check_returned_namespaces
     return 1
   fi
 }
@@ -439,11 +672,13 @@ check_returned_namespaces() {
   local NAMESPACES_IN_K8S
 
   NAMESPACES_IN_RESPONSE="$(run_curl -r "stackgres/namespaces" -n "$CLUSTER_NAMESPACE" \
-    | jq -M -S 'sort_by(.)[]' )"
+    | jq -r -M -S 'sort_by(.)[]' )"
 
-  NAMESPACES_IN_K8S="$(kubectl get ns -o json \
-    | jq -M -S '.items[].metadata.name')"
+  NAMESPACES_IN_K8S="$(
+    [ "x$E2E_ALLOWED_NAMESPACES" != x ] \
+      && printf '%s' "$E2E_ALLOWED_NAMESPACES" | tr ' ' '\n' | sort | uniq \
+      || kubectl get ns -o json \
+    | jq -r -M -S '.items[].metadata.name')"
 
   [ "$NAMESPACES_IN_RESPONSE" = "$NAMESPACES_IN_K8S" ]
 }
-
