e2e: added major version upgrade to zerodowntime runbook

diff --git a/stackgres-k8s/e2e/spec/runbooks/zerodowntime b/stackgres-k8s/e2e/spec/runbooks/zerodowntime
--- a/stackgres-k8s/e2e/spec/runbooks/zerodowntime
+++ b/stackgres-k8s/e2e/spec/runbooks/zerodowntime
@@ -1,5 +1,12 @@
 #!/bin/sh
 
+. "$SPEC_PATH/abstract/dbops-major-version-upgrade"
+
+e2e_test_extra_hash() {
+  "$SHELL" "$PROJECT_PATH/stackgres-k8s/ci/build/build-functions.sh" path_hash \
+    "$(realpath --relative-to "$PROJECT_PATH" "$SPEC_PATH/abstract/dbops-major-version-upgrade")"
+}
+
 e2e_test_install() {
   kubectl create ns "$CLUSTER_NAMESPACE"
 
@@ -9,8 +16,8 @@ e2e_test_install() {
   create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" "2" \
     --set-string 'cluster.postgres.version='"$E2E_MAJOR_SOURCE_POSTGRES_VERSION" \
     --set-string 'cluster.postgres.extensions[0].name=pg_cron' \
-    --set-string 'configurations.postgresconfig.postgresql\.conf.shared_preload_libraries=pg_stat_statements, auto_explain, pg_cron' \
-    --set-string 'configurations.postgresconfig.postgresql\.conf.cron.database_name=postgres' \
+    --set-string 'configurations.postgresconfig.postgresql\.conf.shared_preload_libraries=pg_stat_statements\,auto_explain\,pg_cron' \
+    --set-string 'configurations.postgresconfig.postgresql\.conf.cron\.host=/var/run/postgresql' \
     --set-string 'cluster.configurations.credentials.users.superuser.password.name=credentials' \
     --set-string 'cluster.configurations.credentials.users.superuser.password.key=superuser-password' \
     --set-string 'cluster.configurations.patroni.initialConfig.postgresql.callbacks.on_role_change=/callbacks/pre_promote' \
@@ -43,16 +50,8 @@ kind: Service
 metadata:
   name: entrypoint
 spec:
-  type: ClusterIP
-  ports:
-  - name: pgport
-    port: 5432
-    protocol: TCP
-    targetPort: pgport
-  - name: pgreplication
-    port: 5433
-    protocol: TCP
-    targetPort: pgreplication
+  type: ExternalName
+  externalName: "$CLUSTER_NAME.$CLUSTER_NAMESPACE.svc.cluster.local"
 ---
 apiVersion: v1
 kind: Endpoints
@@ -198,19 +197,14 @@ e2e_test() {
 }
 
 zerodowntime_check() {
-  kubectl patch -n "$CLUSTER_NAMESPACE" endpoints entrypoint --type merge -p '
-    subsets:
-    - addresses:
-      - ip: $(kubectl get service -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME" --template '{{ .spec.clusterIP }}')
-      ports:
-      - name: pgport
-        port: 7432
-        protocol: TCP
-      - name: pgreplication
-        port: 7433
-        protocol: TCP
-  ' -o yaml
   kubectl exec -n "$CLUSTER_NAMESPACE" deploy/pgbouncer -c pgbench -- pgbench postgresql://postgres:sup3rus3r@localhost/postgres -i 2>&1 | tee "$LOG_PATH/bench"
+  if ! grep -q '^command terminated with exit code [1-9]' "$LOG_PATH/bench"
+  then
+    echo "SUCCESS: Benchmark initialized succesfully"
+  else
+    echo "FAIL: Benchmark did not initialized succesfully"
+    return 1
+  fi
   kubectl exec -n "$CLUSTER_NAMESPACE" deploy/pgbouncer -c pgbench -- pgbench postgresql://postgres:sup3rus3r@localhost/postgres -T 120 -c 4 -j 4 -P 2 --progress-timestamp 2>&1 | tee -a "$LOG_PATH/bench" &
   BENCH_PID="$!"
   trap_kill "$BENCH_PID"
@@ -218,7 +212,8 @@ zerodowntime_check() {
     echo $$
     while true
     do
-      date +%s --utc
+      echo
+      echo "# $(date +%s --utc)"
       echo
       kubectl exec -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-0 -c patroni -- env PATRONI_LOG_LEVEL=INFO patronictl list
       echo
@@ -255,28 +250,29 @@ zerodowntime_check() {
   if wait_until eval '! kill -0 "$BENCH_PID"' \
     && ! grep -q '^command terminated with exit code [1-9]' "$LOG_PATH/bench"
   then
-    echo "success Benchmark terminated succesfully without any error after 10 switchovers"
+    echo "SUCCESS: Benchmark terminated succesfully without any error after 10 switchovers"
     kill "$(head -n 1 "$LOG_PATH/monitor")" || true
     wait "$MONITOR_PID" || true
   else
-    echo "success Benchmark do not terminated succesfully after 10 switchovers"
+    echo "FAIL: Benchmark do not terminated succesfully after 10 switchovers"
     kill "$BENCH_PID" || true
     kill "$(head -n 1 "$LOG_PATH/monitor")" || true
     wait "$MONITOR_PID" || true
-    kubectl exec -n "$CLUSTER_NAMESPACE" psql -q\
+    kubectl exec -n "$CLUSTER_NAMESPACE" deploy/pgbouncer -c pgbench \
       -- bash -c 'ps -ef | grep "[p]gbench" | tr -s " " | cut -d " " -f 2 | while read PID; do kill "$PID"; done' || true
     return 1
   fi
 }
 
 zerodowntime_major_version_upgrade_check() {
-  UPGRADED_CLUSTER_NAME=CLUSTER_NAME="$(get_sgcluster_name "$SPEC_NAME-upgraded")"
+  UPGRADED_CLUSTER_NAME="$(get_sgcluster_name "$SPEC_NAME-upgraded")"
   STREAM_NAME="$(get_sgstreams_name "$SPEC_NAME-operation")"
 
   create_or_replace_cluster "$UPGRADED_CLUSTER_NAME" "$CLUSTER_NAMESPACE" "2" \
     --set-string 'cluster.postgres.version='"$E2E_MAJOR_TARGET_POSTGRES_VERSION" \
-    --set prifles=null \
-    --set configurations.create=false \
+    --set instanceProfiles=null \
+    --set configurations.poolingconfig.create=false \
+    --set-string cluster.configurations.sgPostgresConfig=postgresconf-upgraded \
     --set-string 'cluster.configurations.credentials.users.superuser.password.name=credentials' \
     --set-string 'cluster.configurations.credentials.users.superuser.password.key=superuser-password' \
     --set-string 'cluster.configurations.patroni.initialConfig.postgresql.callbacks.on_role_change=/callbacks/pre_promote' \
@@ -289,7 +285,28 @@ zerodowntime_major_version_upgrade_check() {
     --set 'cluster.pods.customVolumes[0].configMap.optional=false'
   wait_cluster "$UPGRADED_CLUSTER_NAME" "$CLUSTER_NAMESPACE"
   kubectl exec -n "$CLUSTER_NAMESPACE" deploy/pgbouncer -c pgbench -- pgbench postgresql://postgres:sup3rus3r@localhost/postgres -i 2>&1 | tee "$LOG_PATH/bench"
-  kubectl exec -n "$CLUSTER_NAMESPACE" deploy/pgbouncer -c pgbench -- pgbench postgresql://postgres:sup3rus3r@localhost/postgres -T 120 -c 4 -j 4 -P 2 --progress-timestamp 2>&1 | tee -a "$LOG_PATH/bench" &
+  if ! grep -q '^command terminated with exit code [1-9]' "$LOG_PATH/bench"
+  then
+    echo "SUCCESS: Benchmark initialized succesfully"
+  else
+    echo "FAIL: Benchmark did not initialized succesfully"
+    return 1
+  fi
+
+  cat << EOF | kubectl exec -i -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-0 -c patroni -- psql -v ON_ERROR_STOP=1 2>&1 | tee "$LOG_PATH/bench"
+ALTER TABLE pgbench_history ADD COLUMN id serial;
+UPDATE pgbench_history SET id = nextval('pgbench_history_id_seq');
+ALTER TABLE pgbench_history ADD PRIMARY KEY(id);
+EOF
+  if ! grep -q '^command terminated with exit code [1-9]' "$LOG_PATH/bench"
+  then
+    echo "SUCCESS: Benchmark initialized succesfully"
+  else
+    echo "FAIL: Benchmark did not initialized succesfully"
+    return 1
+  fi
+
+  kubectl exec -n "$CLUSTER_NAMESPACE" deploy/pgbouncer -c pgbench -- pgbench postgresql://postgres:sup3rus3r@localhost/postgres -T 180 -c 4 -j 4 -P 2 --progress-timestamp 2>&1 | tee -a "$LOG_PATH/bench" &
   BENCH_PID="$!"
   trap_kill "$BENCH_PID"
   CLUSTER_NAMESPACE="$CLUSTER_NAMESPACE" CLUSTER_NAME="$CLUSTER_NAME" UPGRADED_CLUSTER_NAME="$UPGRADED_CLUSTER_NAME" sh -c '
@@ -303,7 +320,7 @@ zerodowntime_major_version_upgrade_check() {
       kubectl exec -n "$CLUSTER_NAMESPACE" "$UPGRADED_CLUSTER_NAME"-0 -c patroni -- env PATRONI_LOG_LEVEL=INFO patronictl list
       echo
       kubectl exec -n "$CLUSTER_NAMESPACE" deploy/pgbouncer -c pgbench -- psql postgresql://pgbouncer_stats:pgb0unc3r@localhost/pgbouncer \
-        -c "SHOW STATE" -c "SHOW DATABASES" -c "SHOW POOLS"
+        -c "SHOW STATE" -c "SHOW DATABASES" -c "SHOW POOLS" -c "SHOW SERVERS"
       echo
       sleep 2
     done' 2>&1 | tee "$LOG_PATH/monitor" &
@@ -325,38 +342,77 @@ spec:
     type: SGCluster
     sgCluster:
       name: "$CLUSTER_NAME"
+      excludes:
+      - cron\..*
   target:
     type: SGCluster
     sgCluster:
-      name: "$TARGET_CLUSTER_NAME"
+      name: "$UPGRADED_CLUSTER_NAME"
   pods:
     persistentVolume:
       size: 1Gi
 EOF
 
-  cat << EOF | kubectl exec -i -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-0 -c patroni -- psql
+  if wait_until eval 'kubectl get sgstream -n "$CLUSTER_NAMESPACE" "$STREAM_NAME" -o json | jq .status.snapshot.snapshotCompleted | grep -qxF true'
+  then
+    echo "SUCCESS: snapshot completed"
+  else
+    echo "FAIL: snapshot did not complete"
+    return 1
+  fi
+
+  cat << 'EOF' | kubectl exec -i -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-0 -c patroni -- psql -v ON_ERROR_STOP=1
 CREATE TABLE heartbit (id serial, time timestamp DEFAULT clock_timestamp(), PRIMARY KEY (id));
+INSERT INTO heartbit DEFAULT VALUES;
 EOF
 
-  for ITERATION in 1 2 3 4 5
-  do
-    kubectl exec -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-0 -c patroni -- env PATRONI_LOG_LEVEL=INFO \
-      patronictl switchover --force "$CLUSTER_NAME" --primary "$CLUSTER_NAME"-0 --candidate "$CLUSTER_NAME"-1
-    sleep 3
-    kubectl exec -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-0 -c patroni -- env PATRONI_LOG_LEVEL=INFO \
-      patronictl restart --force "$CLUSTER_NAME" "$CLUSTER_NAME"-0
-    kubectl exec -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-0 -c patroni -- env PATRONI_LOG_LEVEL=INFO \
-      patronictl restart --force "$CLUSTER_NAME" "$CLUSTER_NAME"-1
-    sleep 3
-    kubectl exec -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-0 -c patroni -- env PATRONI_LOG_LEVEL=INFO \
-      patronictl switchover --force "$CLUSTER_NAME" --primary "$CLUSTER_NAME"-1 --candidate "$CLUSTER_NAME"-0
-    sleep 3
-    kubectl exec -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-0 -c patroni -- env PATRONI_LOG_LEVEL=INFO \
-      patronictl restart --force "$CLUSTER_NAME" "$CLUSTER_NAME"-0
-    kubectl exec -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-0 -c patroni -- env PATRONI_LOG_LEVEL=INFO \
-      patronictl restart --force "$CLUSTER_NAME" "$CLUSTER_NAME"-1
-    sleep 3
-  done
+  if wait_until eval '[ "x$(kubectl exec -i -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-0 -c patroni -- psql -tA -c "SELECT extract(EPOCH from MAX(time))::bigint FROM heartbit")" \
+    = "x$(kubectl exec -i -n "$CLUSTER_NAMESPACE" "$UPGRADED_CLUSTER_NAME"-0 -c patroni -- psql -tA -c "SELECT extract(EPOCH from MAX(time))::bigint FROM heartbit")" ]'
+  then
+    echo "SUCCESS: first heartbit in sync"
+  else
+    echo "FAIL: first heartbit not in sync"
+    return 1
+  fi
+
+  echo "Switching from $CLUSTER_NAME SGCluster ($E2E_MAJOR_SOURCE_POSTGRES_VERSION) to $UPGRADED_CLUSTER_NAME SGCluster ($E2E_MAJOR_TARGET_POSTGRES_VERSION)..."
+  kubectl exec -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-0 -c patroni -- patronictl pause
+  kubectl exec -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-0 -c patroni -- psql postgresql://pgbouncer_admin:pgb0unc3r@pgbouncer/pgbouncer -c PAUSE
+  kubectl patch -n "$CLUSTER_NAMESPACE" service entrypoint --type merge -p "
+  spec:
+    externalName: "$UPGRADED_CLUSTER_NAME.$CLUSTER_NAMESPACE.svc.cluster.local"
+  " -o yaml
+  cat << 'EOF' | kubectl exec -i -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-0 -c patroni -- psql -v ON_ERROR_STOP=1
+INSERT INTO heartbit DEFAULT VALUES;
+EOF
+
+
+  if wait_until eval '[ "x$(kubectl exec -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME"-0 -c patroni -- psql -tA -c "SELECT extract(EPOCH from MAX(time))::bigint FROM heartbit")" \
+    = "x$(kubectl exec -n "$CLUSTER_NAMESPACE" "$UPGRADED_CLUSTER_NAME"-0 -c patroni -- psql -tA -c "SELECT extract(EPOCH from MAX(time))::bigint FROM heartbit")" ]'
+  then
+    echo "SUCCESS: final heartbit in sync"
+  else
+    echo "FAIL: final heartbit not in sync"
+    return 1
+  fi
+
+  kubectl annotate sgstream -n "$CLUSTER_NAMESPACE" "$STREAM_NAME" debezium-signal.stackgres.io/tombstone=
+  if kubectl wait --timeout="${E2E_TIMEOUT}s" sgstream -n "$CLUSTER_NAMESPACE" "$STREAM_NAME" --for=condition=Completed
+  then
+    echo "SUCCESS: stream has completed"
+  else
+    echo "FAIL: stream has not completed"
+    return 1
+  fi
+
+  cat << 'EOF' | kubectl exec -i -n "$CLUSTER_NAMESPACE" "$UPGRADED_CLUSTER_NAME"-0 -c patroni -- psql -v ON_ERROR_STOP=1
+SELECT setval('pgbench_history_id_seq'::regclass, (SELECT MAX(id) + 1 FROM pgbench_history));
+DROP TABLE heartbit;
+EOF
+
+  kubectl exec -n "$CLUSTER_NAMESPACE" "$UPGRADED_CLUSTER_NAME"-0 -c patroni -- psql postgresql://pgbouncer_admin:pgb0unc3r@pgbouncer/pgbouncer -c RESUME
+  echo "...switch to $UPGRADED_CLUSTER_NAME SGCluster ($E2E_MAJOR_TARGET_POSTGRES_VERSION) completed!"
+
   wait "$BENCH_PID"
   if wait_until eval '! kill -0 "$BENCH_PID"' \
     && ! grep -q '^command terminated with exit code [1-9]' "$LOG_PATH/bench"
@@ -365,11 +421,11 @@ EOF
     kill "$(head -n 1 "$LOG_PATH/monitor")" || true
     wait "$MONITOR_PID" || true
   else
-    echo "SUCCESS: Benchmark do not terminated succesfully after 10 switchovers"
+    echo "FAIL: Benchmark do not terminated succesfully after 10 switchovers"
     kill "$BENCH_PID" || true
     kill "$(head -n 1 "$LOG_PATH/monitor")" || true
     wait "$MONITOR_PID" || true
-    kubectl exec -n "$CLUSTER_NAMESPACE" psql \
+    kubectl exec -n "$CLUSTER_NAMESPACE" deploy/pgbouncer -c pgbench \
       -- bash -c 'ps -ef | grep "[p]gbench" | tr -s " " | cut -d " " -f 2 | while read PID; do kill "$PID"; done' || true
     return 1
   fi
