fix: Could not save history to file "/var/lib/postgresql/.psql_history"

diff --git a/stackgres-k8s/e2e/spec/connectivity b/stackgres-k8s/e2e/spec/connectivity
--- a/stackgres-k8s/e2e/spec/connectivity
+++ b/stackgres-k8s/e2e/spec/connectivity
@@ -1,7 +1,13 @@
 #!/bin/sh
 
-e2e_test_install_pods() {
-  echo 2
+. "$SPEC_PATH/abstract/patroni"
+
+e2e_test_install() {
+  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" "2"
+
+  deploy_curl_pod "$CLUSTER_NAMESPACE"
+
+  wait_pods_running "$CLUSTER_NAMESPACE" 3
 }
 
 e2e_test() {
@@ -14,6 +20,8 @@ e2e_test() {
   run_test "Check that patroni management endpoints are not accesible" patroni_management_check
 
   run_test "Check that patroni is not accisible directly" patroni_direct_check
+
+  run_test "Check that psql is storing history in postgres-util container" psql_is_storing_history_check
 }
 
 ports_check() {
@@ -31,14 +39,11 @@ ports_check() {
     RESPONSE_7432="$(run_query -i 1 -p 7432)"
     RESPONSE_7433="$(run_query -i 1 -p 7433)"
 
-    if [ "$RESPONSE_5432" = "1" ] && [ "$RESPONSE_6432" = "1" ] && [ "$RESPONSE_7432" = "1" ] && [ "$RESPONSE_7433" = "1" ]
+    if ! ( [ "$RESPONSE_5432" = "1" ] && [ "$RESPONSE_6432" = "1" ] && [ "$RESPONSE_7432" = "1" ] && [ "$RESPONSE_7433" = "1" ] )
     then
-      return 0
-    else 
       echo "FAIL: Not all 4 ports of the replica node are working"
       return 1
     fi
-
   else 
       echo "FAIL: Not all 4 ports of the primary node are working"
       return 1
@@ -51,19 +56,26 @@ service_check() {
 
   if [ "$RESPONSE_PRIMARY" = "1" ]
   then
-
     RESPONSE_REPLICA="$(run_query -h "$CLUSTER_NAME"-replicas -i 0 -p 5432)"
     if [ "$RESPONSE_REPLICA" = "1" ]
     then
       echo "SUCCESS: Connections are possible using services"
-      return 0
     else
       echo "FAIL: Cannot connect to replica db using a kubernetes service"
       return 1
     fi
-
   else
     echo "FAIL: Cannot connect to primary db using a kubernetes service"
+    return 1
+  fi
+}
+
+psql_is_storing_history_check() {
+  if kubectl exec -t -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME-0" -c postgres-util -- touch /var/lib/postgresql/.psql_history > /dev/null 2>&1
+  then
+    echo "SUCCESS: psql could save history to file"
+  else
+    echo "FAIL: psql could not save history to file"
     return 1
   fi
 }
