feat: Allow to change postgres version/extensions/config at any time and have the operator perform the rollout

diff --git a/stackgres-k8s/e2e/spec/dbops-security-upgrade b/stackgres-k8s/e2e/spec/dbops-security-upgrade
--- a/stackgres-k8s/e2e/spec/dbops-security-upgrade
+++ b/stackgres-k8s/e2e/spec/dbops-security-upgrade
@@ -83,7 +83,7 @@ e2e_test_install() {
   else
     DISTRIBUTEDLOGS_PATRONI_IMAGE="$(printf %s "$PATRONI_IMAGE" | grep '/patroni\(-ext\)\?:v[0-9.]\+-pg12\.')"
   fi
-  DISTRIBUTEDLOGS_PATRONI_IMAGE="$(printf %s "$DISTRIBUTEDLOGS_PATRONI_IMAGE" | grep '/patroni\(-ext\)\?:v[0-9.]\+-pg'"${PREVIOUS_DISTRIBUTEDLOGS_PATRONI_IMAGE_POSTGRES_VERSION%.*}\.${PREVIOUS_DISTRIBUTEDLOGS_PATRONI_IMAGE_POSTGRES_VERSION#*.}-")"
+  DISTRIBUTEDLOGS_PATRONI_IMAGE="$(printf %s "$DISTRIBUTEDLOGS_PATRONI_IMAGE" | grep '/patroni\(-ext\)\?:v[0-9.]\+-pg'"${PREVIOUS_DISTRIBUTEDLOGS_PATRONI_IMAGE_POSTGRES_VERSION%.*}\.[0-9]\+-")"
   DISTRIBUTEDLOGS_PATRONI_IMAGE="$(printf '%s' "$DISTRIBUTEDLOGS_PATRONI_IMAGE" | tail -n 1)"
   PATRONI_IMAGE="$(printf %s "$PATRONI_IMAGE" | grep '/patroni\(-ext\)\?:v[0-9.]\+-pg'"$PREVIOUS_PATRONI_IMAGE_POSTGRES_VERSION-")"
   PATRONI_IMAGE="$(printf '%s' "$PATRONI_IMAGE" | tail -n 1)"
@@ -675,17 +675,6 @@ spec:
 EOF
 
   assert_dbops_running "$DBOPS_NAME" "$CLUSTER_NAMESPACE"
-
-  wait_until eval '[ "$(kubectl get sgcluster -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME" -o json \
-    | jq --argjson timestamp "$(date +%s)" ".metadata.annotations[\"stackgres.io/lockTimeout\"] | . // \"0\" | tonumber - \$timestamp")" -gt 0 ]'
-  if kubectl patch sgcluster -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME" --type json \
-    -p '[{"op":"replace","path":"/spec/metadata","value":{"annotations":{"allResources":{"'"$(random_string)"'": "'"$(random_string)"'"}}}}]' \
-    >/dev/null 2>&1
-  then
-    fail "Cluster has been updated while locked."
-  else
-    success "Cluster has not been updated while locked."
-  fi
 }
 
 check_sharded_cluster_security_upgrade_start() {
@@ -728,17 +717,6 @@ spec:
 EOF
 
   assert_sharded_dbops_running "$DBOPS_NAME" "$CLUSTER_NAMESPACE"
-
-  wait_until eval '[ "$(kubectl get sgcluster -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME" -o json \
-    | jq --argjson timestamp "$(date +%s)" ".metadata.annotations[\"stackgres.io/lockTimeout\"] | . // \"0\" | tonumber - \$timestamp")" -gt 0 ]'
-  if kubectl patch sgshardedcluster -n "$CLUSTER_NAMESPACE" "$SHARDED_CLUSTER_NAME" --type json \
-    -p '[{"op":"replace","path":"/spec/metadata","value":{"annotations":{"allResources":{"'"$(random_string)"'": "'"$(random_string)"'"}}}}]' \
-    >/dev/null 2>&1
-  then
-    fail "Sharded Cluster has been updated while locked."
-  else
-    success "Sharded Cluster has not been updated while locked."
-  fi
 }
 
 check_cluster_before_security_upgrade() {
@@ -954,24 +932,13 @@ check_cluster_after_security_upgrade() {
   else
     fail "Cluster $CLUSTER_NAME is pending upgrade after security upgrade"
   fi
-
-  local STS_UPDATE_REVISION
-  STS_UPDATE_REVISION="$(wait_until kubectl get sts -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME" --template '{{ .status.updateRevision }}')"
-  local POD_CONTROLLER_REVISION_HASH
-  local POD_CONTROLLER_REVISION_HASHES
-  POD_CONTROLLER_REVISION_HASHES="$(kubectl get pod -n "$CLUSTER_NAMESPACE" \
-      -l "app=StackGresCluster,stackgres.io/cluster-name=$CLUSTER_NAME,stackgres.io/cluster=true" -o json \
-    | jq ".items[]|select(.metadata.name | startswith(\"$CLUSTER_NAME\"))" \
-    | jq -r '.metadata.labels."controller-revision-hash"')"
-
-  for POD_CONTROLLER_REVISION_HASH in $POD_CONTROLLER_REVISION_HASHES
-  do
-    if [ "$POD_CONTROLLER_REVISION_HASH" != "$STS_UPDATE_REVISION" ]
-    then
-      echo "FAILURE. Cluster $CLUSTER_NAME security upgrade did not updated successfully some pods"
-      return 1
-    fi
-  done
+  local RESULT EXIT_CODE
+  try_function wait_until check_cluster_pods_are_updated
+  if ! "$RESULT"
+  then
+    echo "FAILURE. Cluster $CLUSTER_NAME security upgrade did not updated successfully some pods"
+    return 1
+  fi
 
   if [ -n "$PATRONI_IMAGE" ]
   then
@@ -1007,6 +974,25 @@ check_cluster_after_security_upgrade() {
     echo "FAILURE. Cluster $CLUSTER_NAME primary service is not of type ExternalName"
     return 1
   fi
+}
+
+check_cluster_pods_are_updated() {
+  local STS_UPDATE_REVISION
+  STS_UPDATE_REVISION="$(wait_until kubectl get sts -n "$CLUSTER_NAMESPACE" "$CLUSTER_NAME" --template '{{ .status.updateRevision }}')"
+  local POD_CONTROLLER_REVISION_HASH
+  local POD_CONTROLLER_REVISION_HASHES
+  POD_CONTROLLER_REVISION_HASHES="$(kubectl get pod -n "$CLUSTER_NAMESPACE" \
+      -l "app=StackGresCluster,stackgres.io/cluster-name=$CLUSTER_NAME,stackgres.io/cluster=true" -o json \
+    | jq ".items[]|select(.metadata.name | startswith(\"$CLUSTER_NAME\"))" \
+    | jq -r '.metadata.labels."controller-revision-hash"')"
+
+  for POD_CONTROLLER_REVISION_HASH in $POD_CONTROLLER_REVISION_HASHES
+  do
+    if [ "$POD_CONTROLLER_REVISION_HASH" != "$STS_UPDATE_REVISION" ]
+    then
+      return 1
+    fi
+  done
 }
 
 check_conversion_webhooks_configured(){
