e2e: add fix to test buggy 1.6.0 operator bundle

diff --git a/stackgres-k8s/e2e/spec/dbops-security-upgrade-olm b/stackgres-k8s/e2e/spec/dbops-security-upgrade-olm
--- a/stackgres-k8s/e2e/spec/dbops-security-upgrade-olm
+++ b/stackgres-k8s/e2e/spec/dbops-security-upgrade-olm
@@ -184,10 +184,116 @@ EOF
     --template "{{ range .items }}{{ if and .status (eq (index .spec.clusterServiceVersionNames 0) \"stackgres.v$BUNDLE_STACKGRES_PREVIOUS_VERSION\") }}{{ printf \"%s\n\" .metadata.name }}{{ end }}{{ end }}" \
     | grep .')"
   kubectl patch -n "$OPERATOR_NAMESPACE" installplan "$INSTALL_PLAN" --type merge -p '{"spec":{"approved":true}}'
-  PREVIOUS_RELEASE_NAME="$(wait_until eval 'kubectl get sgconfig -n "$OPERATOR_NAMESPACE" -o name | grep "^sgconfig.stackgres.io/"')"
+
+  if ! wait_until -t "$((E2E_TIMEOUT * 4))" eval 'kubectl get sgconfig -A -o name | wc -l | grep -qxF 1'
+  then
+    echo "FAILED. The StackGres SGConfig was not found."
+    return 1
+  else
+    echo "SUCCESS. The StackGres SGConfig was found."
+  fi
+
+  PREVIOUS_RELEASE_NAME="$(kubectl get sgconfig -n "$OPERATOR_NAMESPACE" -o name | grep "^sgconfig.stackgres.io/")"
   PREVIOUS_RELEASE_NAME="${PREVIOUS_RELEASE_NAME#*/}"
   kubectl patch -n "$OPERATOR_NAMESPACE" sgconfig "$PREVIOUS_RELEASE_NAME" --type merge \
     -p '{"spec":{"grafana":{"autoEmbed": true, "webHost":"'"prometheus-grafana.$(prometheus_namespace)"'"}}}'
+
+  if [ "$STACKGRES_PREVIOUS_VERSION" = 1.6.0 ]
+  then
+    kubectl create -f "$PROJECT_PATH"/stackgres-k8s/src/common/src/main/resources/crds/SGBackupConfig.yaml
+
+    cat << EOF | kubectl apply -f -
+apiVersion: rbac.authorization.k8s.io/v1
+kind: ClusterRoleBinding
+metadata:
+  name: stackgres-statefulset-controller-extra
+roleRef:
+  apiGroup: rbac.authorization.k8s.io
+  kind: ClusterRole
+  name: stackgres-statefulset-controller-extra
+subjects:
+- kind: ServiceAccount
+  name: statefulset-controller
+  namespace: kube-system
+---
+apiVersion: rbac.authorization.k8s.io/v1
+kind: ClusterRole
+metadata:
+  name: stackgres-statefulset-controller-extra
+rules:
+- apiGroups:
+  - stackgres.io
+  resources:
+  - sgclusters/finalizers
+  verbs:
+  - update
+EOF
+    
+    cat << EOF | kubectl apply -f -
+---
+apiVersion: rbac.authorization.k8s.io/v1
+kind: ClusterRole
+metadata:
+  name: stackgres-operator-extra
+rules:
+- apiGroups: ["stackgres.io"]
+  resources:
+  - sgclusters/finalizers
+  - sgpgconfigs/finalizers
+  - sginstanceprofiles/finalizers
+  - sgpoolconfigs/finalizers
+  - sgbackupconfigs/finalizers
+  - sgbackups/finalizers
+  - sgdistributedlogs/finalizers
+  - sgdbops/finalizers
+  - sgobjectstorages/finalizers
+  - sgscripts/finalizers
+  - sgshardedclusters/finalizers
+  - sgshardedbackups/finalizers
+  - sgshardeddbops/finalizers
+  - sgconfigs/finalizers
+  verbs:
+  - update
+- apiGroups: ["", "apps", "batch"]
+  resources:
+  - statefulsets/finalizers
+  - persistentvolumeclaims/finalizers
+  - deployments/finalizers
+  - services/finalizers
+  - endpoints/finalizers
+  - cronjobs/finalizers
+  - jobs/finalizers
+  verbs:
+  - update
+---
+apiVersion: rbac.authorization.k8s.io/v1
+kind: ClusterRoleBinding
+metadata:
+  name: stackgres-operator-extra
+subjects:
+- kind: ServiceAccount
+  name: stackgres-operator
+  namespace: $OPERATOR_NAMESPACE
+roleRef:
+  kind: ClusterRole
+  name: stackgres-operator-extra
+  apiGroup: rbac.authorization.k8s.io
+EOF
+    
+    kubectl patch -n "$OPERATOR_NAMESPACE" subscription stackgres --type merge -p '
+    {
+      "spec": {
+        "config": {
+          "env":[
+           {
+              "name": "USE_ARBITRARY_USER",
+              "value": "true"
+           }
+           ]
+        }
+      }
+    }'
+  fi
 
   if ! wait_services_available "$OPERATOR_NAMESPACE" 1 "^$PREVIOUS_RELEASE_NAME$"
   then
