chore: fixed e2e tests regarding bkp of clusters without bkp config
Signed-off-by: Guilherme Elias <elias@ongres.com>

diff --git a/stackgres-k8s/e2e/spec/operator-backup-api b/stackgres-k8s/e2e/spec/operator-backup-api
--- a/stackgres-k8s/e2e/spec/operator-backup-api
+++ b/stackgres-k8s/e2e/spec/operator-backup-api
@@ -337,7 +337,9 @@ check_backup_without_config_is_pending() {
   local BACKUP_NAME
   BACKUP_NAME="$(get_sgbackup_name "${CLUSTER_NAME}-pending-$(shuf -i 0-65535 -n 1)")"
 
-  cat << EOF | kubectl create -f -
+  set +e
+
+  RESULT_BACKUP_CREATION="$(cat << EOF | kubectl create -f - 2>&1
   apiVersion: stackgres.io/v1
   kind: SGBackup
   metadata:
@@ -347,22 +349,16 @@ check_backup_without_config_is_pending() {
     sgCluster: "$CLUSTER_NAME-no-backup"
     managedLifecycle: false
 EOF
+)"
 
-  if wait_until eval '[ "$(run_curl -r "stackgres/namespaces/$CLUSTER_NAMESPACE/sgbackups/$BACKUP_NAME" \
-    | jq -r ".status.process.status")" = "Pending" ]'
-  then
-    echo "SUCCESS: backup without configuration get state Pending"
-  else
-    echo "FAIL: backup without configuration didn't get state Pending"
-    return 1
-  fi
+  set -e
 
-  if wait_until eval 'kubectl get event -n "$CLUSTER_NAMESPACE" -o json \
-    | jq -r ".items[] | select(.reason == \"BackupConfigFailed\") | .message" | grep -q "^Missing SGBackupConfig "'
+  if [[ "$RESULT_BACKUP_CREATION" == *"Cluster $CLUSTER_NAME-no-backup has no backup configuration"* ]]
   then
-    echo "SUCCESS: backup without configuration emit missing SGBackupConfig event"
+      echo "SUCCESS: Cluster has no backup configuration"
+      return 0
   else
-    echo "FAIL: backup without configuration didn't emit missing SGBackupConfig event"
-    return 1
+      echo "FAILED: Backup should not be accepted due cluster without backup configuration"
+      return 1  
   fi
 }
