ci: improve pipeline jobs retry

diff --git a/stackgres-k8s/e2e/envs/kind b/stackgres-k8s/e2e/envs/kind
--- a/stackgres-k8s/e2e/envs/kind
+++ b/stackgres-k8s/e2e/envs/kind
@@ -95,7 +95,7 @@ reset_k8s() {
     echo "Setting up kind containerd cache for $KIND_CONTAINERD_CACHE_PATH..."
     if [ "$KIND_CONTAINERD_CACHE_RESET" = true ]
     then
-      docker run -v "$KIND_CONTAINERD_CACHE_PATH:/containerd-cache" alpine \
+      docker run --rm -v "$KIND_CONTAINERD_CACHE_PATH:/containerd-cache" alpine \
         sh -c 'rm -rf /containerd-cache/*'
     fi
   fi
@@ -169,9 +169,15 @@ INNER_EOF
 )
 EOF
 
-  flock "$KIND_LOCK_PATH" \
+  try_function flock "$KIND_LOCK_PATH" \
     kind create cluster --name "$KIND_NAME" --config "$TARGET_PATH/kind-config.yaml" \
     --image "kindest/node:v$(get_kind_image "${K8S_VERSION}")"
+  if ! "$RESULT" && [ -n "$KIND_CONTAINERD_CACHE_PATH" ] && [ "$KIND_CONTAINERD_CACHE_RESET" != true ]
+  then
+    echo "Kind failed to create cluster with cache enabled. Resetting cache and retrying!"
+    KIND_CONTAINERD_CACHE_RESET=true reset_k8s
+    return
+  fi
 
   if [ "$KIND_INSTALL_NFS" = "true" ]
   then
