fix: removed deprecated prometheus-operator helm chart

diff --git a/stackgres-k8s/e2e/utils/helm b/stackgres-k8s/e2e/utils/helm
--- a/stackgres-k8s/e2e/utils/helm
+++ b/stackgres-k8s/e2e/utils/helm
@@ -1,18 +1,36 @@
 #!/bin/sh
 
 setup_helm() {
-  helm repo list | grep -q 'https://kubernetes-charts.storage.googleapis.com' \
-    || helm repo add stable https://kubernetes-charts.storage.googleapis.com
-    
-  helm repo list | grep -q 'https://helm.min.io/' \
-    || helm repo add minio https://helm.min.io/
-      
-  if [ -f "$HOME/.cache/helm/repository/stable-index.yaml" ] \
-    && [ "$(date -u --date="$(grep '^generated:' "$HOME/.cache/helm/repository/stable-index.yaml" \
-    | cut -d ' ' -f 2 | tr 'T' ' ' | tr -d '"' | cut -d . -f 1 || echo 0)" +%s)" -lt "$(($(date +%s) - (60 * 60 * 24)))" ]
+  echo "Helm version $(helm version | cut -d '"' -f 2)"
+  echo
+
+  if helm version | grep -q '^\(3\.[^012]\.\|[^0123]\.\|[1-9][0-9]\+\.\)'
   then
-    helm repo update
+    echo "Helm 3.3+ is required"
+    exit 1
   fi
+
+  local HELM_REPO
+  for HELM_REPO in 'stable|https://charts.helm.sh/stable' \
+    'minio|https://helm.min.io/' \
+    'prometheus-community|https://prometheus-community.github.io/helm-charts'
+  do
+    if ! helm repo list | grep -q "\s${HELM_REPO#*|}\s*$"
+    then
+      if helm repo list | grep -q "^${HELM_REPO%|*}"
+      then
+        helm repo remove "${HELM_REPO%|*}"
+      fi
+      helm repo add "${HELM_REPO%|*}" "${HELM_REPO#*|}"
+    fi
+
+    if [ -f "$HOME/.cache/helm/repository/${HELM_REPO%|*}-index.yaml" ] \
+      && [ "$(stat -c %Y "$HOME/.cache/helm/repository/${HELM_REPO%|*}-index.yaml")" \
+        -lt "$(($(date +%s) - (60 * 60 * 24)))" ]
+    then
+      helm repo update
+    fi
+  done
 
   for CHART_PATH in "$OPERATOR_CHART_PATH" "$CLUSTER_CHART_PATH"
   do
@@ -21,7 +39,4 @@ setup_helm() {
       helm dependency update --skip-refresh "$CHART_PATH"
     fi
   done
-
-  echo "Helm version $(helm version | cut -d '"' -f 2)"
-  echo
 }
