e2e: make the test fail if reinstall_operator_if_not_as_expected fails

diff --git a/stackgres-k8s/e2e/utils/spec b/stackgres-k8s/e2e/utils/spec
--- a/stackgres-k8s/e2e/utils/spec
+++ b/stackgres-k8s/e2e/utils/spec
@@ -144,10 +144,16 @@ spec() {
     return
   fi
 
-  flock "$TARGET_PATH/check-operator-lock" \
-      "$SHELL" $SHELL_XTRACE "$(dirname "$0")/e2e" reinstall_operator_if_not_as_expected
-
   rm -f "$TARGET_PATH/$SPEC_NAME.failed"
+  echo -n > "$LOG_PATH/$SPEC_NAME.log"
+
+  if ! flock "$TARGET_PATH/check-operator-lock" \
+      "$SHELL" $SHELL_XTRACE "$(dirname "$0")/e2e" reinstall_operator_if_not_as_expected >> "$LOG_PATH/$SPEC_NAME.log"
+  then
+    echo "$SPEC_NAME. Operator re-install failed. See file $LOG_PATH/$SPEC_NAME.log for details" > "$TARGET_PATH/$SPEC_NAME.failed"
+    echo "$SPEC_NAME. Operator re-install failed. See file $LOG_PATH/$SPEC_NAME.log for details" >> "$TARGET_PATH/logs/results.log"
+    return 1
+  fi
 
   echo
   echo "================================================================"
@@ -156,7 +162,6 @@ spec() {
   echo
 
   local START="$(date +%s)"
-  echo -n > "$LOG_PATH/$SPEC_NAME.log"
   trap_exec tail -f "$LOG_PATH/$SPEC_NAME.log" \
     | (
     set +x
