feat: store script execution state in the database table managed_sql.status

diff --git a/stackgres-k8s/e2e/spec/previous/1.2/spec/connectivity b/stackgres-k8s/e2e/spec/previous/1.2/spec/connectivity
--- a/stackgres-k8s/e2e/spec/previous/1.2/spec/connectivity
+++ b/stackgres-k8s/e2e/spec/previous/1.2/spec/connectivity
@@ -3,22 +3,17 @@
 . "$SPEC_PATH/abstract/patroni"
 
 e2e_test_install() {
-  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" "1" \
-    --set-string cluster.postgres.version=13.4 \
-    --set-string cluster.postgres.flavor=babelfish \
-    --set-string 'nonProductionOptions.enabledFeatureGates[0]=babelfish-flavor'
+  create_or_replace_cluster "$CLUSTER_NAME" "$CLUSTER_NAMESPACE" "2"
 
   deploy_curl_pod "$CLUSTER_NAMESPACE"
 
-  wait_pods_running "$CLUSTER_NAMESPACE" 2
+  wait_pods_running "$CLUSTER_NAMESPACE" 3
 }
 
 e2e_test() {
-  run_test "Checking that all 6 ports (5432, 1433, 6432, 7432, 7433, 7434) in the patroni pods are opened and listening for queries" ports_check
+  run_test "Checking that all 4 ports (5432, 6432, 7432, 7433) in the patroni pods are openned and listening for queries" ports_check
 
   run_test "Checking that is possible to connect using services is working" service_check
-
-  run_test "Checking that is possible to connect with babelfish protocol using services is working" babelfish_service_check
 
   run_test "Check that patroni healthcheck endpoints are accesible" patroni_ports_check
 
@@ -34,75 +29,35 @@ e2e_test() {
 }
 
 ports_check() {
-  if wait_until single_ports_check
-  then
-    echo "SUCCESS: All 6 ports of the replica node are working"
-  else
-    echo "FAIL: Not all 6 ports of the replica node are working"
-    return 1
-  fi
-}
-
-single_ports_check() {
-  RESPONSE_5432="$(wait_until run_query -i 0 -p 5432)"
-  RESPONSE_1433="$(wait_until run_query -t babelfish -i 0 -p 1433 | tr -d '\n')"
+  RESPONSE_5432="$(run_query -i 0 -p 5432)"
   RESPONSE_6432="$(run_query -i 0 -p 6432)"
   RESPONSE_7432="$(run_query -i 0 -p 7432)"
   RESPONSE_7433="$(run_query -i 0 -p 7433)"
-  RESPONSE_7434="$(run_query -t babelfish -i 0 -p 7434 | tr -d '\n')"
 
-  if [ "$RESPONSE_5432" = "1" ] && [ "$RESPONSE_1433" = "1" ] \
-    && [ "$RESPONSE_6432" = "1" ] && [ "$RESPONSE_7432" = "1" ] && [ "$RESPONSE_7433" = "1" ] && [ "$RESPONSE_7434" = "1" ]
+  if [ "$RESPONSE_5432" = "1" ] && [ "$RESPONSE_6432" = "1" ] && [ "$RESPONSE_7432" = "1" ] && [ "$RESPONSE_7433" = "1" ]
   then
-    echo "Skipping replica check for babelfish"
-    return
-
-    RESPONSE_5432="$(wait_until run_query -i 1 -p 5432)"
-    RESPONSE_1433="$(wait_until run_query -t babelfish -i 1 -p 1433 | tr -d '\n')"
+    RESPONSE_5432="$(run_query -i 1 -p 5432)"
     RESPONSE_6432="$(run_query -i 1 -p 6432)"
     RESPONSE_7432="$(run_query -i 1 -p 7432)"
     RESPONSE_7433="$(run_query -i 1 -p 7433)"
-    RESPONSE_7434="$(run_query -t babelfish -i 1 -p 7434 | tr -d '\n')"
 
-    if ! ( [ "$RESPONSE_5432" = "1" ] && [ "$RESPONSE_1433" = "1" ] \
-      && [ "$RESPONSE_6432" = "1" ] && [ "$RESPONSE_7432" = "1" ] && [ "$RESPONSE_7433" = "1" ] && [ "$RESPONSE_7434" = "1" ] )
+    if ! ( [ "$RESPONSE_5432" = "1" ] && [ "$RESPONSE_6432" = "1" ] && [ "$RESPONSE_7432" = "1" ] && [ "$RESPONSE_7433" = "1" ] )
     then
+      echo "FAIL: Not all 4 ports of the replica node are working"
       return 1
     fi
   else 
+      echo "FAIL: Not all 4 ports of the primary node are working"
       return 1
   fi
 }
 
 service_check() {
-  RESPONSE_PRIMARY="$(run_query -h "$CLUSTER_NAME"-primary -i 0 -p 5432)"
+  RESPONSE_PRIMARY="$(run_query -h "$CLUSTER_NAME"-primary -i 1 -p 5432)"
 
   if [ "$RESPONSE_PRIMARY" = "1" ]
   then
-    echo "Skipping replica check for babelfish"
-    return
-    RESPONSE_REPLICA="$(run_query -h "$CLUSTER_NAME"-replicas -i 1 -p 5432)"
-    if [ "$RESPONSE_REPLICA" = "1" ]
-    then
-      echo "SUCCESS: Connections are possible using services"
-    else
-      echo "FAIL: Cannot connect to replica db using a kubernetes service"
-      return 1
-    fi
-  else
-    echo "FAIL: Cannot connect to primary db using a kubernetes service"
-    return 1
-  fi
-}
-
-babelfish_service_check() {
-  RESPONSE_PRIMARY="$(run_query -t babelfish -h "$CLUSTER_NAME"-primary -i 0 -p 1433 | tr -d '\n')"
-
-  if [ "$RESPONSE_PRIMARY" = "1" ]
-  then
-    echo "Skipping replica check for babelfish"
-    return
-    RESPONSE_REPLICA="$(run_query -t babelfish -h "$CLUSTER_NAME"-replicas -i 1 -p 1433 | tr -d '\n')"
+    RESPONSE_REPLICA="$(run_query -h "$CLUSTER_NAME"-replicas -i 0 -p 5432)"
     if [ "$RESPONSE_REPLICA" = "1" ]
     then
       echo "SUCCESS: Connections are possible using services"
@@ -160,9 +115,9 @@ pgbouncer_users_check() {
     | kubectl patch sgpoolconfig -n "$CLUSTER_NAMESPACE" pgbouncerconf --type merge -p "$(cat)"
   wait_until eval '! kubectl wait -n "$CLUSTER_NAMESPACE" "sgcluster/$CLUSTER_NAME" --for condition=PendingRestart --timeout 0'
   kubectl delete pod -n "$CLUSTER_NAMESPACE" -l "app=StackGresCluster,stackgres.io/cluster-name=$CLUSTER_NAME,stackgres.io/cluster=true"
-  wait_pods_running "$CLUSTER_NAMESPACE" 2
+  wait_pods_running "$CLUSTER_NAMESPACE" 3
 
-  RESPONSE_REPLICA="$(run_query -h "$CLUSTER_NAME"-primary -i 0 -p 5432 -u user1:test)"
+  RESPONSE_REPLICA="$(run_query -h "$CLUSTER_NAME"-primary -i 1 -p 5432 -u user1:test)"
   if [ "$RESPONSE_REPLICA" = "1" ]
   then
     echo "SUCCESS: Connections are possible using user1 in pgbouncer users section"
@@ -171,7 +126,7 @@ pgbouncer_users_check() {
     return 1
   fi
 
-  RESPONSE_REPLICA="$(run_query -h "$CLUSTER_NAME"-primary -i 0 -p 5432 -u user2:test)"
+  RESPONSE_REPLICA="$(run_query -h "$CLUSTER_NAME"-primary -i 1 -p 5432 -u user2:test)"
   if [ "$RESPONSE_REPLICA" = "1" ]
   then
     echo "SUCCESS: Connections are possible using user2 in pgbouncer users section"
